// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbpostgres

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// AccessToken is an object representing the database table.
type AccessToken struct {
	ID             string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	TenantID       string      `boil:"tenant_id" json:"tenant_id" toml:"tenant_id" yaml:"tenant_id"`
	TokenHash      []byte      `boil:"token_hash" json:"token_hash" toml:"token_hash" yaml:"token_hash"`
	UserID         string      `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	CreatedAt      time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	ExpiresAt      null.Time   `boil:"expires_at" json:"expires_at,omitempty" toml:"expires_at" yaml:"expires_at,omitempty"`
	RevokedAt      null.Time   `boil:"revoked_at" json:"revoked_at,omitempty" toml:"revoked_at" yaml:"revoked_at,omitempty"`
	DeviceID       string      `boil:"device_id" json:"device_id" toml:"device_id" yaml:"device_id"`
	RefreshTokenID null.String `boil:"refresh_token_id" json:"refresh_token_id,omitempty" toml:"refresh_token_id" yaml:"refresh_token_id,omitempty"`

	R *accessTokenR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L accessTokenL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AccessTokenColumns = struct {
	ID             string
	TenantID       string
	TokenHash      string
	UserID         string
	CreatedAt      string
	ExpiresAt      string
	RevokedAt      string
	DeviceID       string
	RefreshTokenID string
}{
	ID:             "id",
	TenantID:       "tenant_id",
	TokenHash:      "token_hash",
	UserID:         "user_id",
	CreatedAt:      "created_at",
	ExpiresAt:      "expires_at",
	RevokedAt:      "revoked_at",
	DeviceID:       "device_id",
	RefreshTokenID: "refresh_token_id",
}

var AccessTokenTableColumns = struct {
	ID             string
	TenantID       string
	TokenHash      string
	UserID         string
	CreatedAt      string
	ExpiresAt      string
	RevokedAt      string
	DeviceID       string
	RefreshTokenID string
}{
	ID:             "access_tokens.id",
	TenantID:       "access_tokens.tenant_id",
	TokenHash:      "access_tokens.token_hash",
	UserID:         "access_tokens.user_id",
	CreatedAt:      "access_tokens.created_at",
	ExpiresAt:      "access_tokens.expires_at",
	RevokedAt:      "access_tokens.revoked_at",
	DeviceID:       "access_tokens.device_id",
	RefreshTokenID: "access_tokens.refresh_token_id",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod    { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod   { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod   { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) SIMILAR(x string) qm.QueryMod { return qm.Where(w.field+" SIMILAR TO ?", x) }
func (w whereHelperstring) NSIMILAR(x string) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelper__byte struct{ field string }

func (w whereHelper__byte) EQ(x []byte) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelper__byte) NEQ(x []byte) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelper__byte) LT(x []byte) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelper__byte) LTE(x []byte) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelper__byte) GT(x []byte) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelper__byte) GTE(x []byte) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

type whereHelpernull_Time struct{ field string }

func (w whereHelpernull_Time) EQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Time) NEQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Time) LT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Time) LTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Time) GT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Time) GTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_Time) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Time) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpernull_String struct{ field string }

func (w whereHelpernull_String) EQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_String) NEQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_String) LT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_String) LTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_String) GT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_String) GTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_String) LIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" LIKE ?", x)
}
func (w whereHelpernull_String) NLIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT LIKE ?", x)
}
func (w whereHelpernull_String) ILIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" ILIKE ?", x)
}
func (w whereHelpernull_String) NILIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT ILIKE ?", x)
}
func (w whereHelpernull_String) SIMILAR(x null.String) qm.QueryMod {
	return qm.Where(w.field+" SIMILAR TO ?", x)
}
func (w whereHelpernull_String) NSIMILAR(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelpernull_String) IN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_String) NIN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_String) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_String) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var AccessTokenWhere = struct {
	ID             whereHelperstring
	TenantID       whereHelperstring
	TokenHash      whereHelper__byte
	UserID         whereHelperstring
	CreatedAt      whereHelpertime_Time
	ExpiresAt      whereHelpernull_Time
	RevokedAt      whereHelpernull_Time
	DeviceID       whereHelperstring
	RefreshTokenID whereHelpernull_String
}{
	ID:             whereHelperstring{field: "\"access_tokens\".\"id\""},
	TenantID:       whereHelperstring{field: "\"access_tokens\".\"tenant_id\""},
	TokenHash:      whereHelper__byte{field: "\"access_tokens\".\"token_hash\""},
	UserID:         whereHelperstring{field: "\"access_tokens\".\"user_id\""},
	CreatedAt:      whereHelpertime_Time{field: "\"access_tokens\".\"created_at\""},
	ExpiresAt:      whereHelpernull_Time{field: "\"access_tokens\".\"expires_at\""},
	RevokedAt:      whereHelpernull_Time{field: "\"access_tokens\".\"revoked_at\""},
	DeviceID:       whereHelperstring{field: "\"access_tokens\".\"device_id\""},
	RefreshTokenID: whereHelpernull_String{field: "\"access_tokens\".\"refresh_token_id\""},
}

// AccessTokenRels is where relationship names are stored.
var AccessTokenRels = struct {
	RefreshToken string
	Tenant       string
}{
	RefreshToken: "RefreshToken",
	Tenant:       "Tenant",
}

// accessTokenR is where relationships are stored.
type accessTokenR struct {
	RefreshToken *RefreshToken `boil:"RefreshToken" json:"RefreshToken" toml:"RefreshToken" yaml:"RefreshToken"`
	Tenant       *Tenant       `boil:"Tenant" json:"Tenant" toml:"Tenant" yaml:"Tenant"`
}

// NewStruct creates a new relationship struct
func (*accessTokenR) NewStruct() *accessTokenR {
	return &accessTokenR{}
}

func (o *AccessToken) GetRefreshToken() *RefreshToken {
	if o == nil {
		return nil
	}

	return o.R.GetRefreshToken()
}

func (r *accessTokenR) GetRefreshToken() *RefreshToken {
	if r == nil {
		return nil
	}

	return r.RefreshToken
}

func (o *AccessToken) GetTenant() *Tenant {
	if o == nil {
		return nil
	}

	return o.R.GetTenant()
}

func (r *accessTokenR) GetTenant() *Tenant {
	if r == nil {
		return nil
	}

	return r.Tenant
}

// accessTokenL is where Load methods for each relationship are stored.
type accessTokenL struct{}

var (
	accessTokenAllColumns            = []string{"id", "tenant_id", "token_hash", "user_id", "created_at", "expires_at", "revoked_at", "device_id", "refresh_token_id"}
	accessTokenColumnsWithoutDefault = []string{"tenant_id", "token_hash", "user_id"}
	accessTokenColumnsWithDefault    = []string{"id", "created_at", "expires_at", "revoked_at", "device_id", "refresh_token_id"}
	accessTokenPrimaryKeyColumns     = []string{"id"}
	accessTokenGeneratedColumns      = []string{}
)

type (
	// AccessTokenSlice is an alias for a slice of pointers to AccessToken.
	// This should almost always be used instead of []AccessToken.
	AccessTokenSlice []*AccessToken
	// AccessTokenHook is the signature for custom AccessToken hook methods
	AccessTokenHook func(context.Context, boil.ContextExecutor, *AccessToken) error

	accessTokenQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	accessTokenType                 = reflect.TypeOf(&AccessToken{})
	accessTokenMapping              = queries.MakeStructMapping(accessTokenType)
	accessTokenPrimaryKeyMapping, _ = queries.BindMapping(accessTokenType, accessTokenMapping, accessTokenPrimaryKeyColumns)
	accessTokenInsertCacheMut       sync.RWMutex
	accessTokenInsertCache          = make(map[string]insertCache)
	accessTokenUpdateCacheMut       sync.RWMutex
	accessTokenUpdateCache          = make(map[string]updateCache)
	accessTokenUpsertCacheMut       sync.RWMutex
	accessTokenUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var accessTokenAfterSelectMu sync.Mutex
var accessTokenAfterSelectHooks []AccessTokenHook

var accessTokenBeforeInsertMu sync.Mutex
var accessTokenBeforeInsertHooks []AccessTokenHook
var accessTokenAfterInsertMu sync.Mutex
var accessTokenAfterInsertHooks []AccessTokenHook

var accessTokenBeforeUpdateMu sync.Mutex
var accessTokenBeforeUpdateHooks []AccessTokenHook
var accessTokenAfterUpdateMu sync.Mutex
var accessTokenAfterUpdateHooks []AccessTokenHook

var accessTokenBeforeDeleteMu sync.Mutex
var accessTokenBeforeDeleteHooks []AccessTokenHook
var accessTokenAfterDeleteMu sync.Mutex
var accessTokenAfterDeleteHooks []AccessTokenHook

var accessTokenBeforeUpsertMu sync.Mutex
var accessTokenBeforeUpsertHooks []AccessTokenHook
var accessTokenAfterUpsertMu sync.Mutex
var accessTokenAfterUpsertHooks []AccessTokenHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *AccessToken) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessTokenAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *AccessToken) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessTokenBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *AccessToken) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessTokenAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *AccessToken) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessTokenBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *AccessToken) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessTokenAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *AccessToken) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessTokenBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *AccessToken) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessTokenAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *AccessToken) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessTokenBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *AccessToken) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range accessTokenAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddAccessTokenHook registers your hook function for all future operations.
func AddAccessTokenHook(hookPoint boil.HookPoint, accessTokenHook AccessTokenHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		accessTokenAfterSelectMu.Lock()
		accessTokenAfterSelectHooks = append(accessTokenAfterSelectHooks, accessTokenHook)
		accessTokenAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		accessTokenBeforeInsertMu.Lock()
		accessTokenBeforeInsertHooks = append(accessTokenBeforeInsertHooks, accessTokenHook)
		accessTokenBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		accessTokenAfterInsertMu.Lock()
		accessTokenAfterInsertHooks = append(accessTokenAfterInsertHooks, accessTokenHook)
		accessTokenAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		accessTokenBeforeUpdateMu.Lock()
		accessTokenBeforeUpdateHooks = append(accessTokenBeforeUpdateHooks, accessTokenHook)
		accessTokenBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		accessTokenAfterUpdateMu.Lock()
		accessTokenAfterUpdateHooks = append(accessTokenAfterUpdateHooks, accessTokenHook)
		accessTokenAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		accessTokenBeforeDeleteMu.Lock()
		accessTokenBeforeDeleteHooks = append(accessTokenBeforeDeleteHooks, accessTokenHook)
		accessTokenBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		accessTokenAfterDeleteMu.Lock()
		accessTokenAfterDeleteHooks = append(accessTokenAfterDeleteHooks, accessTokenHook)
		accessTokenAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		accessTokenBeforeUpsertMu.Lock()
		accessTokenBeforeUpsertHooks = append(accessTokenBeforeUpsertHooks, accessTokenHook)
		accessTokenBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		accessTokenAfterUpsertMu.Lock()
		accessTokenAfterUpsertHooks = append(accessTokenAfterUpsertHooks, accessTokenHook)
		accessTokenAfterUpsertMu.Unlock()
	}
}

// One returns a single accessToken record from the query.
func (q accessTokenQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AccessToken, error) {
	o := &AccessToken{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: failed to execute a one query for access_tokens")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all AccessToken records from the query.
func (q accessTokenQuery) All(ctx context.Context, exec boil.ContextExecutor) (AccessTokenSlice, error) {
	var o []*AccessToken

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbpostgres: failed to assign all query results to AccessToken slice")
	}

	if len(accessTokenAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all AccessToken records in the query.
func (q accessTokenQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to count access_tokens rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q accessTokenQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: failed to check if access_tokens exists")
	}

	return count > 0, nil
}

// RefreshToken pointed to by the foreign key.
func (o *AccessToken) RefreshToken(mods ...qm.QueryMod) refreshTokenQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.RefreshTokenID),
	}

	queryMods = append(queryMods, mods...)

	return RefreshTokens(queryMods...)
}

// Tenant pointed to by the foreign key.
func (o *AccessToken) Tenant(mods ...qm.QueryMod) tenantQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.TenantID),
	}

	queryMods = append(queryMods, mods...)

	return Tenants(queryMods...)
}

// LoadRefreshToken allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (accessTokenL) LoadRefreshToken(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAccessToken any, mods queries.Applicator) error {
	var slice []*AccessToken
	var object *AccessToken

	if singular {
		var ok bool
		object, ok = maybeAccessToken.(*AccessToken)
		if !ok {
			object = new(AccessToken)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAccessToken)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAccessToken))
			}
		}
	} else {
		s, ok := maybeAccessToken.(*[]*AccessToken)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAccessToken)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAccessToken))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &accessTokenR{}
		}
		if !queries.IsNil(object.RefreshTokenID) {
			args[object.RefreshTokenID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &accessTokenR{}
			}

			if !queries.IsNil(obj.RefreshTokenID) {
				args[obj.RefreshTokenID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`refresh_tokens`),
		qm.WhereIn(`refresh_tokens.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load RefreshToken")
	}

	var resultSlice []*RefreshToken
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice RefreshToken")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for refresh_tokens")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for refresh_tokens")
	}

	if len(refreshTokenAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.RefreshToken = foreign
		if foreign.R == nil {
			foreign.R = &refreshTokenR{}
		}
		foreign.R.AccessTokens = append(foreign.R.AccessTokens, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.RefreshTokenID, foreign.ID) {
				local.R.RefreshToken = foreign
				if foreign.R == nil {
					foreign.R = &refreshTokenR{}
				}
				foreign.R.AccessTokens = append(foreign.R.AccessTokens, local)
				break
			}
		}
	}

	return nil
}

// LoadTenant allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (accessTokenL) LoadTenant(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAccessToken any, mods queries.Applicator) error {
	var slice []*AccessToken
	var object *AccessToken

	if singular {
		var ok bool
		object, ok = maybeAccessToken.(*AccessToken)
		if !ok {
			object = new(AccessToken)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAccessToken)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAccessToken))
			}
		}
	} else {
		s, ok := maybeAccessToken.(*[]*AccessToken)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAccessToken)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAccessToken))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &accessTokenR{}
		}
		args[object.TenantID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &accessTokenR{}
			}

			args[obj.TenantID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tenants`),
		qm.WhereIn(`tenants.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Tenant")
	}

	var resultSlice []*Tenant
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Tenant")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for tenants")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tenants")
	}

	if len(tenantAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Tenant = foreign
		if foreign.R == nil {
			foreign.R = &tenantR{}
		}
		foreign.R.AccessTokens = append(foreign.R.AccessTokens, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.TenantID == foreign.ID {
				local.R.Tenant = foreign
				if foreign.R == nil {
					foreign.R = &tenantR{}
				}
				foreign.R.AccessTokens = append(foreign.R.AccessTokens, local)
				break
			}
		}
	}

	return nil
}

// SetRefreshToken of the accessToken to the related item.
// Sets o.R.RefreshToken to related.
// Adds o to related.R.AccessTokens.
func (o *AccessToken) SetRefreshToken(ctx context.Context, exec boil.ContextExecutor, insert bool, related *RefreshToken) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"access_tokens\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"refresh_token_id"}),
		strmangle.WhereClause("\"", "\"", 2, accessTokenPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.RefreshTokenID, related.ID)
	if o.R == nil {
		o.R = &accessTokenR{
			RefreshToken: related,
		}
	} else {
		o.R.RefreshToken = related
	}

	if related.R == nil {
		related.R = &refreshTokenR{
			AccessTokens: AccessTokenSlice{o},
		}
	} else {
		related.R.AccessTokens = append(related.R.AccessTokens, o)
	}

	return nil
}

// RemoveRefreshToken relationship.
// Sets o.R.RefreshToken to nil.
// Removes o from all passed in related items' relationships struct.
func (o *AccessToken) RemoveRefreshToken(ctx context.Context, exec boil.ContextExecutor, related *RefreshToken) error {
	var err error

	queries.SetScanner(&o.RefreshTokenID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("refresh_token_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.RefreshToken = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.AccessTokens {
		if queries.Equal(o.RefreshTokenID, ri.RefreshTokenID) {
			continue
		}

		ln := len(related.R.AccessTokens)
		if ln > 1 && i < ln-1 {
			related.R.AccessTokens[i] = related.R.AccessTokens[ln-1]
		}
		related.R.AccessTokens = related.R.AccessTokens[:ln-1]
		break
	}
	return nil
}

// SetTenant of the accessToken to the related item.
// Sets o.R.Tenant to related.
// Adds o to related.R.AccessTokens.
func (o *AccessToken) SetTenant(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Tenant) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"access_tokens\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"tenant_id"}),
		strmangle.WhereClause("\"", "\"", 2, accessTokenPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.TenantID = related.ID
	if o.R == nil {
		o.R = &accessTokenR{
			Tenant: related,
		}
	} else {
		o.R.Tenant = related
	}

	if related.R == nil {
		related.R = &tenantR{
			AccessTokens: AccessTokenSlice{o},
		}
	} else {
		related.R.AccessTokens = append(related.R.AccessTokens, o)
	}

	return nil
}

// AccessTokens retrieves all the records using an executor.
func AccessTokens(mods ...qm.QueryMod) accessTokenQuery {
	mods = append(mods, qm.From("\"access_tokens\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"access_tokens\".*"})
	}

	return accessTokenQuery{q}
}

// FindAccessToken retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAccessToken(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*AccessToken, error) {
	accessTokenObj := &AccessToken{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"access_tokens\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, accessTokenObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: unable to select from access_tokens")
	}

	if err = accessTokenObj.doAfterSelectHooks(ctx, exec); err != nil {
		return accessTokenObj, err
	}

	return accessTokenObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AccessToken) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbpostgres: no access_tokens provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(accessTokenColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	accessTokenInsertCacheMut.RLock()
	cache, cached := accessTokenInsertCache[key]
	accessTokenInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			accessTokenAllColumns,
			accessTokenColumnsWithDefault,
			accessTokenColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(accessTokenType, accessTokenMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(accessTokenType, accessTokenMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"access_tokens\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"access_tokens\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to insert into access_tokens")
	}

	if !cached {
		accessTokenInsertCacheMut.Lock()
		accessTokenInsertCache[key] = cache
		accessTokenInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the AccessToken.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AccessToken) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	accessTokenUpdateCacheMut.RLock()
	cache, cached := accessTokenUpdateCache[key]
	accessTokenUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			accessTokenAllColumns,
			accessTokenPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbpostgres: unable to update access_tokens, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"access_tokens\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, accessTokenPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(accessTokenType, accessTokenMapping, append(wl, accessTokenPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update access_tokens row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by update for access_tokens")
	}

	if !cached {
		accessTokenUpdateCacheMut.Lock()
		accessTokenUpdateCache[key] = cache
		accessTokenUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q accessTokenQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all for access_tokens")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected for access_tokens")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AccessTokenSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbpostgres: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accessTokenPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"access_tokens\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, accessTokenPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all in accessToken slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected all in update all accessToken")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *AccessToken) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbpostgres: no access_tokens provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(accessTokenColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	accessTokenUpsertCacheMut.RLock()
	cache, cached := accessTokenUpsertCache[key]
	accessTokenUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			accessTokenAllColumns,
			accessTokenColumnsWithDefault,
			accessTokenColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			accessTokenAllColumns,
			accessTokenPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbpostgres: unable to upsert access_tokens, could not build update column list")
		}

		ret := strmangle.SetComplement(accessTokenAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(accessTokenPrimaryKeyColumns) == 0 {
				return errors.New("dbpostgres: unable to upsert access_tokens, could not build conflict column list")
			}

			conflict = make([]string, len(accessTokenPrimaryKeyColumns))
			copy(conflict, accessTokenPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"access_tokens\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(accessTokenType, accessTokenMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(accessTokenType, accessTokenMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to upsert access_tokens")
	}

	if !cached {
		accessTokenUpsertCacheMut.Lock()
		accessTokenUpsertCache[key] = cache
		accessTokenUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single AccessToken record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AccessToken) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbpostgres: no AccessToken provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), accessTokenPrimaryKeyMapping)
	sql := "DELETE FROM \"access_tokens\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete from access_tokens")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by delete for access_tokens")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q accessTokenQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbpostgres: no accessTokenQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from access_tokens")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for access_tokens")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AccessTokenSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(accessTokenBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accessTokenPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"access_tokens\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accessTokenPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from accessToken slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for access_tokens")
	}

	if len(accessTokenAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AccessToken) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAccessToken(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AccessTokenSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AccessTokenSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), accessTokenPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"access_tokens\".* FROM \"access_tokens\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, accessTokenPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to reload all in AccessTokenSlice")
	}

	*o = slice

	return nil
}

// AccessTokenExists checks if the AccessToken row exists.
func AccessTokenExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"access_tokens\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: unable to check if access_tokens exists")
	}

	return exists, nil
}

// Exists checks if the AccessToken row exists.
func (o *AccessToken) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return AccessTokenExists(ctx, exec, o.ID)
}
