// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbpostgres

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// EventStateKey is an object representing the database table.
type EventStateKey struct {
	EventStateKeyNid int64  `boil:"event_state_key_nid" json:"event_state_key_nid" toml:"event_state_key_nid" yaml:"event_state_key_nid"`
	EventStateKey    string `boil:"event_state_key" json:"event_state_key" toml:"event_state_key" yaml:"event_state_key"`

	R *eventStateKeyR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L eventStateKeyL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var EventStateKeyColumns = struct {
	EventStateKeyNid string
	EventStateKey    string
}{
	EventStateKeyNid: "event_state_key_nid",
	EventStateKey:    "event_state_key",
}

var EventStateKeyTableColumns = struct {
	EventStateKeyNid string
	EventStateKey    string
}{
	EventStateKeyNid: "event_state_keys.event_state_key_nid",
	EventStateKey:    "event_state_keys.event_state_key",
}

// Generated where

var EventStateKeyWhere = struct {
	EventStateKeyNid whereHelperint64
	EventStateKey    whereHelperstring
}{
	EventStateKeyNid: whereHelperint64{field: "\"event_state_keys\".\"event_state_key_nid\""},
	EventStateKey:    whereHelperstring{field: "\"event_state_keys\".\"event_state_key\""},
}

// EventStateKeyRels is where relationship names are stored.
var EventStateKeyRels = struct {
	EventStateKeyNidEvents            string
	EventStateKeyNidStateBlockEntries string
}{
	EventStateKeyNidEvents:            "EventStateKeyNidEvents",
	EventStateKeyNidStateBlockEntries: "EventStateKeyNidStateBlockEntries",
}

// eventStateKeyR is where relationships are stored.
type eventStateKeyR struct {
	EventStateKeyNidEvents            EventSlice           `boil:"EventStateKeyNidEvents" json:"EventStateKeyNidEvents" toml:"EventStateKeyNidEvents" yaml:"EventStateKeyNidEvents"`
	EventStateKeyNidStateBlockEntries StateBlockEntrySlice `boil:"EventStateKeyNidStateBlockEntries" json:"EventStateKeyNidStateBlockEntries" toml:"EventStateKeyNidStateBlockEntries" yaml:"EventStateKeyNidStateBlockEntries"`
}

// NewStruct creates a new relationship struct
func (*eventStateKeyR) NewStruct() *eventStateKeyR {
	return &eventStateKeyR{}
}

func (o *EventStateKey) GetEventStateKeyNidEvents() EventSlice {
	if o == nil {
		return nil
	}

	return o.R.GetEventStateKeyNidEvents()
}

func (r *eventStateKeyR) GetEventStateKeyNidEvents() EventSlice {
	if r == nil {
		return nil
	}

	return r.EventStateKeyNidEvents
}

func (o *EventStateKey) GetEventStateKeyNidStateBlockEntries() StateBlockEntrySlice {
	if o == nil {
		return nil
	}

	return o.R.GetEventStateKeyNidStateBlockEntries()
}

func (r *eventStateKeyR) GetEventStateKeyNidStateBlockEntries() StateBlockEntrySlice {
	if r == nil {
		return nil
	}

	return r.EventStateKeyNidStateBlockEntries
}

// eventStateKeyL is where Load methods for each relationship are stored.
type eventStateKeyL struct{}

var (
	eventStateKeyAllColumns            = []string{"event_state_key_nid", "event_state_key"}
	eventStateKeyColumnsWithoutDefault = []string{"event_state_key"}
	eventStateKeyColumnsWithDefault    = []string{"event_state_key_nid"}
	eventStateKeyPrimaryKeyColumns     = []string{"event_state_key_nid"}
	eventStateKeyGeneratedColumns      = []string{}
)

type (
	// EventStateKeySlice is an alias for a slice of pointers to EventStateKey.
	// This should almost always be used instead of []EventStateKey.
	EventStateKeySlice []*EventStateKey
	// EventStateKeyHook is the signature for custom EventStateKey hook methods
	EventStateKeyHook func(context.Context, boil.ContextExecutor, *EventStateKey) error

	eventStateKeyQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	eventStateKeyType                 = reflect.TypeOf(&EventStateKey{})
	eventStateKeyMapping              = queries.MakeStructMapping(eventStateKeyType)
	eventStateKeyPrimaryKeyMapping, _ = queries.BindMapping(eventStateKeyType, eventStateKeyMapping, eventStateKeyPrimaryKeyColumns)
	eventStateKeyInsertCacheMut       sync.RWMutex
	eventStateKeyInsertCache          = make(map[string]insertCache)
	eventStateKeyUpdateCacheMut       sync.RWMutex
	eventStateKeyUpdateCache          = make(map[string]updateCache)
	eventStateKeyUpsertCacheMut       sync.RWMutex
	eventStateKeyUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var eventStateKeyAfterSelectMu sync.Mutex
var eventStateKeyAfterSelectHooks []EventStateKeyHook

var eventStateKeyBeforeInsertMu sync.Mutex
var eventStateKeyBeforeInsertHooks []EventStateKeyHook
var eventStateKeyAfterInsertMu sync.Mutex
var eventStateKeyAfterInsertHooks []EventStateKeyHook

var eventStateKeyBeforeUpdateMu sync.Mutex
var eventStateKeyBeforeUpdateHooks []EventStateKeyHook
var eventStateKeyAfterUpdateMu sync.Mutex
var eventStateKeyAfterUpdateHooks []EventStateKeyHook

var eventStateKeyBeforeDeleteMu sync.Mutex
var eventStateKeyBeforeDeleteHooks []EventStateKeyHook
var eventStateKeyAfterDeleteMu sync.Mutex
var eventStateKeyAfterDeleteHooks []EventStateKeyHook

var eventStateKeyBeforeUpsertMu sync.Mutex
var eventStateKeyBeforeUpsertHooks []EventStateKeyHook
var eventStateKeyAfterUpsertMu sync.Mutex
var eventStateKeyAfterUpsertHooks []EventStateKeyHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *EventStateKey) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventStateKeyAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *EventStateKey) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventStateKeyBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *EventStateKey) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventStateKeyAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *EventStateKey) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventStateKeyBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *EventStateKey) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventStateKeyAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *EventStateKey) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventStateKeyBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *EventStateKey) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventStateKeyAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *EventStateKey) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventStateKeyBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *EventStateKey) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventStateKeyAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddEventStateKeyHook registers your hook function for all future operations.
func AddEventStateKeyHook(hookPoint boil.HookPoint, eventStateKeyHook EventStateKeyHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		eventStateKeyAfterSelectMu.Lock()
		eventStateKeyAfterSelectHooks = append(eventStateKeyAfterSelectHooks, eventStateKeyHook)
		eventStateKeyAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		eventStateKeyBeforeInsertMu.Lock()
		eventStateKeyBeforeInsertHooks = append(eventStateKeyBeforeInsertHooks, eventStateKeyHook)
		eventStateKeyBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		eventStateKeyAfterInsertMu.Lock()
		eventStateKeyAfterInsertHooks = append(eventStateKeyAfterInsertHooks, eventStateKeyHook)
		eventStateKeyAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		eventStateKeyBeforeUpdateMu.Lock()
		eventStateKeyBeforeUpdateHooks = append(eventStateKeyBeforeUpdateHooks, eventStateKeyHook)
		eventStateKeyBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		eventStateKeyAfterUpdateMu.Lock()
		eventStateKeyAfterUpdateHooks = append(eventStateKeyAfterUpdateHooks, eventStateKeyHook)
		eventStateKeyAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		eventStateKeyBeforeDeleteMu.Lock()
		eventStateKeyBeforeDeleteHooks = append(eventStateKeyBeforeDeleteHooks, eventStateKeyHook)
		eventStateKeyBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		eventStateKeyAfterDeleteMu.Lock()
		eventStateKeyAfterDeleteHooks = append(eventStateKeyAfterDeleteHooks, eventStateKeyHook)
		eventStateKeyAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		eventStateKeyBeforeUpsertMu.Lock()
		eventStateKeyBeforeUpsertHooks = append(eventStateKeyBeforeUpsertHooks, eventStateKeyHook)
		eventStateKeyBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		eventStateKeyAfterUpsertMu.Lock()
		eventStateKeyAfterUpsertHooks = append(eventStateKeyAfterUpsertHooks, eventStateKeyHook)
		eventStateKeyAfterUpsertMu.Unlock()
	}
}

// One returns a single eventStateKey record from the query.
func (q eventStateKeyQuery) One(ctx context.Context, exec boil.ContextExecutor) (*EventStateKey, error) {
	o := &EventStateKey{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: failed to execute a one query for event_state_keys")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all EventStateKey records from the query.
func (q eventStateKeyQuery) All(ctx context.Context, exec boil.ContextExecutor) (EventStateKeySlice, error) {
	var o []*EventStateKey

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbpostgres: failed to assign all query results to EventStateKey slice")
	}

	if len(eventStateKeyAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all EventStateKey records in the query.
func (q eventStateKeyQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to count event_state_keys rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q eventStateKeyQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: failed to check if event_state_keys exists")
	}

	return count > 0, nil
}

// EventStateKeyNidEvents retrieves all the event's Events with an executor via event_state_key_nid column.
func (o *EventStateKey) EventStateKeyNidEvents(mods ...qm.QueryMod) eventQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"events\".\"event_state_key_nid\"=?", o.EventStateKeyNid),
	)

	return Events(queryMods...)
}

// EventStateKeyNidStateBlockEntries retrieves all the state_block_entry's StateBlockEntries with an executor via event_state_key_nid column.
func (o *EventStateKey) EventStateKeyNidStateBlockEntries(mods ...qm.QueryMod) stateBlockEntryQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"state_block_entries\".\"event_state_key_nid\"=?", o.EventStateKeyNid),
	)

	return StateBlockEntries(queryMods...)
}

// LoadEventStateKeyNidEvents allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (eventStateKeyL) LoadEventStateKeyNidEvents(ctx context.Context, e boil.ContextExecutor, singular bool, maybeEventStateKey any, mods queries.Applicator) error {
	var slice []*EventStateKey
	var object *EventStateKey

	if singular {
		var ok bool
		object, ok = maybeEventStateKey.(*EventStateKey)
		if !ok {
			object = new(EventStateKey)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeEventStateKey)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeEventStateKey))
			}
		}
	} else {
		s, ok := maybeEventStateKey.(*[]*EventStateKey)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeEventStateKey)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeEventStateKey))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &eventStateKeyR{}
		}
		args[object.EventStateKeyNid] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &eventStateKeyR{}
			}
			args[obj.EventStateKeyNid] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`events`),
		qm.WhereIn(`events.event_state_key_nid in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load events")
	}

	var resultSlice []*Event
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice events")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on events")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for events")
	}

	if len(eventAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.EventStateKeyNidEvents = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &eventR{}
			}
			foreign.R.EventStateKeyNidEventStateKey = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.EventStateKeyNid, foreign.EventStateKeyNid) {
				local.R.EventStateKeyNidEvents = append(local.R.EventStateKeyNidEvents, foreign)
				if foreign.R == nil {
					foreign.R = &eventR{}
				}
				foreign.R.EventStateKeyNidEventStateKey = local
				break
			}
		}
	}

	return nil
}

// LoadEventStateKeyNidStateBlockEntries allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (eventStateKeyL) LoadEventStateKeyNidStateBlockEntries(ctx context.Context, e boil.ContextExecutor, singular bool, maybeEventStateKey any, mods queries.Applicator) error {
	var slice []*EventStateKey
	var object *EventStateKey

	if singular {
		var ok bool
		object, ok = maybeEventStateKey.(*EventStateKey)
		if !ok {
			object = new(EventStateKey)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeEventStateKey)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeEventStateKey))
			}
		}
	} else {
		s, ok := maybeEventStateKey.(*[]*EventStateKey)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeEventStateKey)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeEventStateKey))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &eventStateKeyR{}
		}
		args[object.EventStateKeyNid] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &eventStateKeyR{}
			}
			args[obj.EventStateKeyNid] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`state_block_entries`),
		qm.WhereIn(`state_block_entries.event_state_key_nid in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load state_block_entries")
	}

	var resultSlice []*StateBlockEntry
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice state_block_entries")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on state_block_entries")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for state_block_entries")
	}

	if len(stateBlockEntryAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.EventStateKeyNidStateBlockEntries = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &stateBlockEntryR{}
			}
			foreign.R.EventStateKeyNidEventStateKey = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.EventStateKeyNid == foreign.EventStateKeyNid {
				local.R.EventStateKeyNidStateBlockEntries = append(local.R.EventStateKeyNidStateBlockEntries, foreign)
				if foreign.R == nil {
					foreign.R = &stateBlockEntryR{}
				}
				foreign.R.EventStateKeyNidEventStateKey = local
				break
			}
		}
	}

	return nil
}

// AddEventStateKeyNidEvents adds the given related objects to the existing relationships
// of the event_state_key, optionally inserting them as new records.
// Appends related to o.R.EventStateKeyNidEvents.
// Sets related.R.EventStateKeyNidEventStateKey appropriately.
func (o *EventStateKey) AddEventStateKeyNidEvents(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Event) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.EventStateKeyNid, o.EventStateKeyNid)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"events\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"event_state_key_nid"}),
				strmangle.WhereClause("\"", "\"", 2, eventPrimaryKeyColumns),
			)
			values := []any{o.EventStateKeyNid, rel.EventNid}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.EventStateKeyNid, o.EventStateKeyNid)
		}
	}

	if o.R == nil {
		o.R = &eventStateKeyR{
			EventStateKeyNidEvents: related,
		}
	} else {
		o.R.EventStateKeyNidEvents = append(o.R.EventStateKeyNidEvents, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &eventR{
				EventStateKeyNidEventStateKey: o,
			}
		} else {
			rel.R.EventStateKeyNidEventStateKey = o
		}
	}
	return nil
}

// SetEventStateKeyNidEvents removes all previously related items of the
// event_state_key replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.EventStateKeyNidEventStateKey's EventStateKeyNidEvents accordingly.
// Replaces o.R.EventStateKeyNidEvents with related.
// Sets related.R.EventStateKeyNidEventStateKey's EventStateKeyNidEvents accordingly.
func (o *EventStateKey) SetEventStateKeyNidEvents(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Event) error {
	query := "update \"events\" set \"event_state_key_nid\" = null where \"event_state_key_nid\" = $1"
	values := []any{o.EventStateKeyNid}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.EventStateKeyNidEvents {
			queries.SetScanner(&rel.EventStateKeyNid, nil)
			if rel.R == nil {
				continue
			}

			rel.R.EventStateKeyNidEventStateKey = nil
		}
		o.R.EventStateKeyNidEvents = nil
	}

	return o.AddEventStateKeyNidEvents(ctx, exec, insert, related...)
}

// RemoveEventStateKeyNidEvents relationships from objects passed in.
// Removes related items from R.EventStateKeyNidEvents (uses pointer comparison, removal does not keep order)
// Sets related.R.EventStateKeyNidEventStateKey.
func (o *EventStateKey) RemoveEventStateKeyNidEvents(ctx context.Context, exec boil.ContextExecutor, related ...*Event) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.EventStateKeyNid, nil)
		if rel.R != nil {
			rel.R.EventStateKeyNidEventStateKey = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("event_state_key_nid")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.EventStateKeyNidEvents {
			if rel != ri {
				continue
			}

			ln := len(o.R.EventStateKeyNidEvents)
			if ln > 1 && i < ln-1 {
				o.R.EventStateKeyNidEvents[i] = o.R.EventStateKeyNidEvents[ln-1]
			}
			o.R.EventStateKeyNidEvents = o.R.EventStateKeyNidEvents[:ln-1]
			break
		}
	}

	return nil
}

// AddEventStateKeyNidStateBlockEntries adds the given related objects to the existing relationships
// of the event_state_key, optionally inserting them as new records.
// Appends related to o.R.EventStateKeyNidStateBlockEntries.
// Sets related.R.EventStateKeyNidEventStateKey appropriately.
func (o *EventStateKey) AddEventStateKeyNidStateBlockEntries(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*StateBlockEntry) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.EventStateKeyNid = o.EventStateKeyNid
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"state_block_entries\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"event_state_key_nid"}),
				strmangle.WhereClause("\"", "\"", 2, stateBlockEntryPrimaryKeyColumns),
			)
			values := []any{o.EventStateKeyNid, rel.StateBlockNid, rel.EventTypeNid, rel.EventStateKeyNid}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.EventStateKeyNid = o.EventStateKeyNid
		}
	}

	if o.R == nil {
		o.R = &eventStateKeyR{
			EventStateKeyNidStateBlockEntries: related,
		}
	} else {
		o.R.EventStateKeyNidStateBlockEntries = append(o.R.EventStateKeyNidStateBlockEntries, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &stateBlockEntryR{
				EventStateKeyNidEventStateKey: o,
			}
		} else {
			rel.R.EventStateKeyNidEventStateKey = o
		}
	}
	return nil
}

// EventStateKeys retrieves all the records using an executor.
func EventStateKeys(mods ...qm.QueryMod) eventStateKeyQuery {
	mods = append(mods, qm.From("\"event_state_keys\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"event_state_keys\".*"})
	}

	return eventStateKeyQuery{q}
}

// FindEventStateKey retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindEventStateKey(ctx context.Context, exec boil.ContextExecutor, eventStateKeyNid int64, selectCols ...string) (*EventStateKey, error) {
	eventStateKeyObj := &EventStateKey{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"event_state_keys\" where \"event_state_key_nid\"=$1", sel,
	)

	q := queries.Raw(query, eventStateKeyNid)

	err := q.Bind(ctx, exec, eventStateKeyObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: unable to select from event_state_keys")
	}

	if err = eventStateKeyObj.doAfterSelectHooks(ctx, exec); err != nil {
		return eventStateKeyObj, err
	}

	return eventStateKeyObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *EventStateKey) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbpostgres: no event_state_keys provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(eventStateKeyColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	eventStateKeyInsertCacheMut.RLock()
	cache, cached := eventStateKeyInsertCache[key]
	eventStateKeyInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			eventStateKeyAllColumns,
			eventStateKeyColumnsWithDefault,
			eventStateKeyColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(eventStateKeyType, eventStateKeyMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(eventStateKeyType, eventStateKeyMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"event_state_keys\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"event_state_keys\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to insert into event_state_keys")
	}

	if !cached {
		eventStateKeyInsertCacheMut.Lock()
		eventStateKeyInsertCache[key] = cache
		eventStateKeyInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the EventStateKey.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *EventStateKey) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	eventStateKeyUpdateCacheMut.RLock()
	cache, cached := eventStateKeyUpdateCache[key]
	eventStateKeyUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			eventStateKeyAllColumns,
			eventStateKeyPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbpostgres: unable to update event_state_keys, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"event_state_keys\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, eventStateKeyPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(eventStateKeyType, eventStateKeyMapping, append(wl, eventStateKeyPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update event_state_keys row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by update for event_state_keys")
	}

	if !cached {
		eventStateKeyUpdateCacheMut.Lock()
		eventStateKeyUpdateCache[key] = cache
		eventStateKeyUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q eventStateKeyQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all for event_state_keys")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected for event_state_keys")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o EventStateKeySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbpostgres: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), eventStateKeyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"event_state_keys\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, eventStateKeyPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all in eventStateKey slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected all in update all eventStateKey")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *EventStateKey) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbpostgres: no event_state_keys provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(eventStateKeyColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	eventStateKeyUpsertCacheMut.RLock()
	cache, cached := eventStateKeyUpsertCache[key]
	eventStateKeyUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			eventStateKeyAllColumns,
			eventStateKeyColumnsWithDefault,
			eventStateKeyColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			eventStateKeyAllColumns,
			eventStateKeyPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbpostgres: unable to upsert event_state_keys, could not build update column list")
		}

		ret := strmangle.SetComplement(eventStateKeyAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(eventStateKeyPrimaryKeyColumns) == 0 {
				return errors.New("dbpostgres: unable to upsert event_state_keys, could not build conflict column list")
			}

			conflict = make([]string, len(eventStateKeyPrimaryKeyColumns))
			copy(conflict, eventStateKeyPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"event_state_keys\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(eventStateKeyType, eventStateKeyMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(eventStateKeyType, eventStateKeyMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to upsert event_state_keys")
	}

	if !cached {
		eventStateKeyUpsertCacheMut.Lock()
		eventStateKeyUpsertCache[key] = cache
		eventStateKeyUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single EventStateKey record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *EventStateKey) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbpostgres: no EventStateKey provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), eventStateKeyPrimaryKeyMapping)
	sql := "DELETE FROM \"event_state_keys\" WHERE \"event_state_key_nid\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete from event_state_keys")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by delete for event_state_keys")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q eventStateKeyQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbpostgres: no eventStateKeyQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from event_state_keys")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for event_state_keys")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o EventStateKeySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(eventStateKeyBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), eventStateKeyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"event_state_keys\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, eventStateKeyPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from eventStateKey slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for event_state_keys")
	}

	if len(eventStateKeyAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *EventStateKey) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindEventStateKey(ctx, exec, o.EventStateKeyNid)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EventStateKeySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := EventStateKeySlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), eventStateKeyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"event_state_keys\".* FROM \"event_state_keys\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, eventStateKeyPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to reload all in EventStateKeySlice")
	}

	*o = slice

	return nil
}

// EventStateKeyExists checks if the EventStateKey row exists.
func EventStateKeyExists(ctx context.Context, exec boil.ContextExecutor, eventStateKeyNid int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"event_state_keys\" where \"event_state_key_nid\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, eventStateKeyNid)
	}
	row := exec.QueryRowContext(ctx, sql, eventStateKeyNid)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: unable to check if event_state_keys exists")
	}

	return exists, nil
}

// Exists checks if the EventStateKey row exists.
func (o *EventStateKey) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return EventStateKeyExists(ctx, exec, o.EventStateKeyNid)
}
