// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbpostgres

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Receipt is an object representing the database table.
type Receipt struct {
	TenantID    string `boil:"tenant_id" json:"tenant_id" toml:"tenant_id" yaml:"tenant_id"`
	RoomNid     int64  `boil:"room_nid" json:"room_nid" toml:"room_nid" yaml:"room_nid"`
	UserID      string `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	ReceiptType string `boil:"receipt_type" json:"receipt_type" toml:"receipt_type" yaml:"receipt_type"`
	ThreadID    string `boil:"thread_id" json:"thread_id" toml:"thread_id" yaml:"thread_id"`
	EventNid    int64  `boil:"event_nid" json:"event_nid" toml:"event_nid" yaml:"event_nid"`
	TS          int64  `boil:"ts" json:"ts" toml:"ts" yaml:"ts"`
	StreamID    int64  `boil:"stream_id" json:"stream_id" toml:"stream_id" yaml:"stream_id"`

	R *receiptR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L receiptL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ReceiptColumns = struct {
	TenantID    string
	RoomNid     string
	UserID      string
	ReceiptType string
	ThreadID    string
	EventNid    string
	TS          string
	StreamID    string
}{
	TenantID:    "tenant_id",
	RoomNid:     "room_nid",
	UserID:      "user_id",
	ReceiptType: "receipt_type",
	ThreadID:    "thread_id",
	EventNid:    "event_nid",
	TS:          "ts",
	StreamID:    "stream_id",
}

var ReceiptTableColumns = struct {
	TenantID    string
	RoomNid     string
	UserID      string
	ReceiptType string
	ThreadID    string
	EventNid    string
	TS          string
	StreamID    string
}{
	TenantID:    "receipts.tenant_id",
	RoomNid:     "receipts.room_nid",
	UserID:      "receipts.user_id",
	ReceiptType: "receipts.receipt_type",
	ThreadID:    "receipts.thread_id",
	EventNid:    "receipts.event_nid",
	TS:          "receipts.ts",
	StreamID:    "receipts.stream_id",
}

// Generated where

var ReceiptWhere = struct {
	TenantID    whereHelperstring
	RoomNid     whereHelperint64
	UserID      whereHelperstring
	ReceiptType whereHelperstring
	ThreadID    whereHelperstring
	EventNid    whereHelperint64
	TS          whereHelperint64
	StreamID    whereHelperint64
}{
	TenantID:    whereHelperstring{field: "\"receipts\".\"tenant_id\""},
	RoomNid:     whereHelperint64{field: "\"receipts\".\"room_nid\""},
	UserID:      whereHelperstring{field: "\"receipts\".\"user_id\""},
	ReceiptType: whereHelperstring{field: "\"receipts\".\"receipt_type\""},
	ThreadID:    whereHelperstring{field: "\"receipts\".\"thread_id\""},
	EventNid:    whereHelperint64{field: "\"receipts\".\"event_nid\""},
	TS:          whereHelperint64{field: "\"receipts\".\"ts\""},
	StreamID:    whereHelperint64{field: "\"receipts\".\"stream_id\""},
}

// ReceiptRels is where relationship names are stored.
var ReceiptRels = struct {
	EventNidEvent string
	RoomNidRoom   string
}{
	EventNidEvent: "EventNidEvent",
	RoomNidRoom:   "RoomNidRoom",
}

// receiptR is where relationships are stored.
type receiptR struct {
	EventNidEvent *Event `boil:"EventNidEvent" json:"EventNidEvent" toml:"EventNidEvent" yaml:"EventNidEvent"`
	RoomNidRoom   *Room  `boil:"RoomNidRoom" json:"RoomNidRoom" toml:"RoomNidRoom" yaml:"RoomNidRoom"`
}

// NewStruct creates a new relationship struct
func (*receiptR) NewStruct() *receiptR {
	return &receiptR{}
}

func (o *Receipt) GetEventNidEvent() *Event {
	if o == nil {
		return nil
	}

	return o.R.GetEventNidEvent()
}

func (r *receiptR) GetEventNidEvent() *Event {
	if r == nil {
		return nil
	}

	return r.EventNidEvent
}

func (o *Receipt) GetRoomNidRoom() *Room {
	if o == nil {
		return nil
	}

	return o.R.GetRoomNidRoom()
}

func (r *receiptR) GetRoomNidRoom() *Room {
	if r == nil {
		return nil
	}

	return r.RoomNidRoom
}

// receiptL is where Load methods for each relationship are stored.
type receiptL struct{}

var (
	receiptAllColumns            = []string{"tenant_id", "room_nid", "user_id", "receipt_type", "thread_id", "event_nid", "ts", "stream_id"}
	receiptColumnsWithoutDefault = []string{"tenant_id", "room_nid", "user_id", "receipt_type", "thread_id", "event_nid", "ts", "stream_id"}
	receiptColumnsWithDefault    = []string{}
	receiptPrimaryKeyColumns     = []string{"tenant_id", "room_nid", "user_id", "receipt_type", "thread_id"}
	receiptGeneratedColumns      = []string{}
)

type (
	// ReceiptSlice is an alias for a slice of pointers to Receipt.
	// This should almost always be used instead of []Receipt.
	ReceiptSlice []*Receipt
	// ReceiptHook is the signature for custom Receipt hook methods
	ReceiptHook func(context.Context, boil.ContextExecutor, *Receipt) error

	receiptQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	receiptType                 = reflect.TypeOf(&Receipt{})
	receiptMapping              = queries.MakeStructMapping(receiptType)
	receiptPrimaryKeyMapping, _ = queries.BindMapping(receiptType, receiptMapping, receiptPrimaryKeyColumns)
	receiptInsertCacheMut       sync.RWMutex
	receiptInsertCache          = make(map[string]insertCache)
	receiptUpdateCacheMut       sync.RWMutex
	receiptUpdateCache          = make(map[string]updateCache)
	receiptUpsertCacheMut       sync.RWMutex
	receiptUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var receiptAfterSelectMu sync.Mutex
var receiptAfterSelectHooks []ReceiptHook

var receiptBeforeInsertMu sync.Mutex
var receiptBeforeInsertHooks []ReceiptHook
var receiptAfterInsertMu sync.Mutex
var receiptAfterInsertHooks []ReceiptHook

var receiptBeforeUpdateMu sync.Mutex
var receiptBeforeUpdateHooks []ReceiptHook
var receiptAfterUpdateMu sync.Mutex
var receiptAfterUpdateHooks []ReceiptHook

var receiptBeforeDeleteMu sync.Mutex
var receiptBeforeDeleteHooks []ReceiptHook
var receiptAfterDeleteMu sync.Mutex
var receiptAfterDeleteHooks []ReceiptHook

var receiptBeforeUpsertMu sync.Mutex
var receiptBeforeUpsertHooks []ReceiptHook
var receiptAfterUpsertMu sync.Mutex
var receiptAfterUpsertHooks []ReceiptHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Receipt) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range receiptAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Receipt) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range receiptBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Receipt) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range receiptAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Receipt) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range receiptBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Receipt) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range receiptAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Receipt) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range receiptBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Receipt) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range receiptAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Receipt) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range receiptBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Receipt) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range receiptAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddReceiptHook registers your hook function for all future operations.
func AddReceiptHook(hookPoint boil.HookPoint, receiptHook ReceiptHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		receiptAfterSelectMu.Lock()
		receiptAfterSelectHooks = append(receiptAfterSelectHooks, receiptHook)
		receiptAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		receiptBeforeInsertMu.Lock()
		receiptBeforeInsertHooks = append(receiptBeforeInsertHooks, receiptHook)
		receiptBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		receiptAfterInsertMu.Lock()
		receiptAfterInsertHooks = append(receiptAfterInsertHooks, receiptHook)
		receiptAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		receiptBeforeUpdateMu.Lock()
		receiptBeforeUpdateHooks = append(receiptBeforeUpdateHooks, receiptHook)
		receiptBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		receiptAfterUpdateMu.Lock()
		receiptAfterUpdateHooks = append(receiptAfterUpdateHooks, receiptHook)
		receiptAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		receiptBeforeDeleteMu.Lock()
		receiptBeforeDeleteHooks = append(receiptBeforeDeleteHooks, receiptHook)
		receiptBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		receiptAfterDeleteMu.Lock()
		receiptAfterDeleteHooks = append(receiptAfterDeleteHooks, receiptHook)
		receiptAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		receiptBeforeUpsertMu.Lock()
		receiptBeforeUpsertHooks = append(receiptBeforeUpsertHooks, receiptHook)
		receiptBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		receiptAfterUpsertMu.Lock()
		receiptAfterUpsertHooks = append(receiptAfterUpsertHooks, receiptHook)
		receiptAfterUpsertMu.Unlock()
	}
}

// One returns a single receipt record from the query.
func (q receiptQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Receipt, error) {
	o := &Receipt{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: failed to execute a one query for receipts")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Receipt records from the query.
func (q receiptQuery) All(ctx context.Context, exec boil.ContextExecutor) (ReceiptSlice, error) {
	var o []*Receipt

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbpostgres: failed to assign all query results to Receipt slice")
	}

	if len(receiptAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Receipt records in the query.
func (q receiptQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to count receipts rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q receiptQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: failed to check if receipts exists")
	}

	return count > 0, nil
}

// EventNidEvent pointed to by the foreign key.
func (o *Receipt) EventNidEvent(mods ...qm.QueryMod) eventQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"event_nid\" = ?", o.EventNid),
	}

	queryMods = append(queryMods, mods...)

	return Events(queryMods...)
}

// RoomNidRoom pointed to by the foreign key.
func (o *Receipt) RoomNidRoom(mods ...qm.QueryMod) roomQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"room_nid\" = ?", o.RoomNid),
	}

	queryMods = append(queryMods, mods...)

	return Rooms(queryMods...)
}

// LoadEventNidEvent allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (receiptL) LoadEventNidEvent(ctx context.Context, e boil.ContextExecutor, singular bool, maybeReceipt any, mods queries.Applicator) error {
	var slice []*Receipt
	var object *Receipt

	if singular {
		var ok bool
		object, ok = maybeReceipt.(*Receipt)
		if !ok {
			object = new(Receipt)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeReceipt)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeReceipt))
			}
		}
	} else {
		s, ok := maybeReceipt.(*[]*Receipt)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeReceipt)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeReceipt))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &receiptR{}
		}
		args[object.EventNid] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &receiptR{}
			}

			args[obj.EventNid] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`events`),
		qm.WhereIn(`events.event_nid in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Event")
	}

	var resultSlice []*Event
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Event")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for events")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for events")
	}

	if len(eventAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.EventNidEvent = foreign
		if foreign.R == nil {
			foreign.R = &eventR{}
		}
		foreign.R.EventNidReceipts = append(foreign.R.EventNidReceipts, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.EventNid == foreign.EventNid {
				local.R.EventNidEvent = foreign
				if foreign.R == nil {
					foreign.R = &eventR{}
				}
				foreign.R.EventNidReceipts = append(foreign.R.EventNidReceipts, local)
				break
			}
		}
	}

	return nil
}

// LoadRoomNidRoom allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (receiptL) LoadRoomNidRoom(ctx context.Context, e boil.ContextExecutor, singular bool, maybeReceipt any, mods queries.Applicator) error {
	var slice []*Receipt
	var object *Receipt

	if singular {
		var ok bool
		object, ok = maybeReceipt.(*Receipt)
		if !ok {
			object = new(Receipt)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeReceipt)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeReceipt))
			}
		}
	} else {
		s, ok := maybeReceipt.(*[]*Receipt)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeReceipt)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeReceipt))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &receiptR{}
		}
		args[object.RoomNid] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &receiptR{}
			}

			args[obj.RoomNid] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`rooms`),
		qm.WhereIn(`rooms.room_nid in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Room")
	}

	var resultSlice []*Room
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Room")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for rooms")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for rooms")
	}

	if len(roomAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.RoomNidRoom = foreign
		if foreign.R == nil {
			foreign.R = &roomR{}
		}
		foreign.R.RoomNidReceipts = append(foreign.R.RoomNidReceipts, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.RoomNid == foreign.RoomNid {
				local.R.RoomNidRoom = foreign
				if foreign.R == nil {
					foreign.R = &roomR{}
				}
				foreign.R.RoomNidReceipts = append(foreign.R.RoomNidReceipts, local)
				break
			}
		}
	}

	return nil
}

// SetEventNidEvent of the receipt to the related item.
// Sets o.R.EventNidEvent to related.
// Adds o to related.R.EventNidReceipts.
func (o *Receipt) SetEventNidEvent(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Event) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"receipts\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"event_nid"}),
		strmangle.WhereClause("\"", "\"", 2, receiptPrimaryKeyColumns),
	)
	values := []any{related.EventNid, o.TenantID, o.RoomNid, o.UserID, o.ReceiptType, o.ThreadID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.EventNid = related.EventNid
	if o.R == nil {
		o.R = &receiptR{
			EventNidEvent: related,
		}
	} else {
		o.R.EventNidEvent = related
	}

	if related.R == nil {
		related.R = &eventR{
			EventNidReceipts: ReceiptSlice{o},
		}
	} else {
		related.R.EventNidReceipts = append(related.R.EventNidReceipts, o)
	}

	return nil
}

// SetRoomNidRoom of the receipt to the related item.
// Sets o.R.RoomNidRoom to related.
// Adds o to related.R.RoomNidReceipts.
func (o *Receipt) SetRoomNidRoom(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Room) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"receipts\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"room_nid"}),
		strmangle.WhereClause("\"", "\"", 2, receiptPrimaryKeyColumns),
	)
	values := []any{related.RoomNid, o.TenantID, o.RoomNid, o.UserID, o.ReceiptType, o.ThreadID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.RoomNid = related.RoomNid
	if o.R == nil {
		o.R = &receiptR{
			RoomNidRoom: related,
		}
	} else {
		o.R.RoomNidRoom = related
	}

	if related.R == nil {
		related.R = &roomR{
			RoomNidReceipts: ReceiptSlice{o},
		}
	} else {
		related.R.RoomNidReceipts = append(related.R.RoomNidReceipts, o)
	}

	return nil
}

// Receipts retrieves all the records using an executor.
func Receipts(mods ...qm.QueryMod) receiptQuery {
	mods = append(mods, qm.From("\"receipts\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"receipts\".*"})
	}

	return receiptQuery{q}
}

// FindReceipt retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindReceipt(ctx context.Context, exec boil.ContextExecutor, tenantID string, roomNid int64, userID string, receiptType string, threadID string, selectCols ...string) (*Receipt, error) {
	receiptObj := &Receipt{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"receipts\" where \"tenant_id\"=$1 AND \"room_nid\"=$2 AND \"user_id\"=$3 AND \"receipt_type\"=$4 AND \"thread_id\"=$5", sel,
	)

	q := queries.Raw(query, tenantID, roomNid, userID, receiptType, threadID)

	err := q.Bind(ctx, exec, receiptObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: unable to select from receipts")
	}

	if err = receiptObj.doAfterSelectHooks(ctx, exec); err != nil {
		return receiptObj, err
	}

	return receiptObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Receipt) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbpostgres: no receipts provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(receiptColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	receiptInsertCacheMut.RLock()
	cache, cached := receiptInsertCache[key]
	receiptInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			receiptAllColumns,
			receiptColumnsWithDefault,
			receiptColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(receiptType, receiptMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(receiptType, receiptMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"receipts\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"receipts\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to insert into receipts")
	}

	if !cached {
		receiptInsertCacheMut.Lock()
		receiptInsertCache[key] = cache
		receiptInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Receipt.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Receipt) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	receiptUpdateCacheMut.RLock()
	cache, cached := receiptUpdateCache[key]
	receiptUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			receiptAllColumns,
			receiptPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbpostgres: unable to update receipts, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"receipts\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, receiptPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(receiptType, receiptMapping, append(wl, receiptPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update receipts row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by update for receipts")
	}

	if !cached {
		receiptUpdateCacheMut.Lock()
		receiptUpdateCache[key] = cache
		receiptUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q receiptQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all for receipts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected for receipts")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ReceiptSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbpostgres: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), receiptPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"receipts\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, receiptPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all in receipt slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected all in update all receipt")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Receipt) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbpostgres: no receipts provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(receiptColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	receiptUpsertCacheMut.RLock()
	cache, cached := receiptUpsertCache[key]
	receiptUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			receiptAllColumns,
			receiptColumnsWithDefault,
			receiptColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			receiptAllColumns,
			receiptPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbpostgres: unable to upsert receipts, could not build update column list")
		}

		ret := strmangle.SetComplement(receiptAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(receiptPrimaryKeyColumns) == 0 {
				return errors.New("dbpostgres: unable to upsert receipts, could not build conflict column list")
			}

			conflict = make([]string, len(receiptPrimaryKeyColumns))
			copy(conflict, receiptPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"receipts\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(receiptType, receiptMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(receiptType, receiptMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to upsert receipts")
	}

	if !cached {
		receiptUpsertCacheMut.Lock()
		receiptUpsertCache[key] = cache
		receiptUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Receipt record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Receipt) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbpostgres: no Receipt provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), receiptPrimaryKeyMapping)
	sql := "DELETE FROM \"receipts\" WHERE \"tenant_id\"=$1 AND \"room_nid\"=$2 AND \"user_id\"=$3 AND \"receipt_type\"=$4 AND \"thread_id\"=$5"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete from receipts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by delete for receipts")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q receiptQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbpostgres: no receiptQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from receipts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for receipts")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ReceiptSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(receiptBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), receiptPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"receipts\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, receiptPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from receipt slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for receipts")
	}

	if len(receiptAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Receipt) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindReceipt(ctx, exec, o.TenantID, o.RoomNid, o.UserID, o.ReceiptType, o.ThreadID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ReceiptSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ReceiptSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), receiptPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"receipts\".* FROM \"receipts\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, receiptPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to reload all in ReceiptSlice")
	}

	*o = slice

	return nil
}

// ReceiptExists checks if the Receipt row exists.
func ReceiptExists(ctx context.Context, exec boil.ContextExecutor, tenantID string, roomNid int64, userID string, receiptType string, threadID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"receipts\" where \"tenant_id\"=$1 AND \"room_nid\"=$2 AND \"user_id\"=$3 AND \"receipt_type\"=$4 AND \"thread_id\"=$5 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, tenantID, roomNid, userID, receiptType, threadID)
	}
	row := exec.QueryRowContext(ctx, sql, tenantID, roomNid, userID, receiptType, threadID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: unable to check if receipts exists")
	}

	return exists, nil
}

// Exists checks if the Receipt row exists.
func (o *Receipt) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ReceiptExists(ctx, exec, o.TenantID, o.RoomNid, o.UserID, o.ReceiptType, o.ThreadID)
}
