// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbpostgres

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Room is an object representing the database table.
type Room struct {
	RoomNid        int64      `boil:"room_nid" json:"room_nid" toml:"room_nid" yaml:"room_nid"`
	TenantID       string     `boil:"tenant_id" json:"tenant_id" toml:"tenant_id" yaml:"tenant_id"`
	RoomID         string     `boil:"room_id" json:"room_id" toml:"room_id" yaml:"room_id"`
	RoomVersion    string     `boil:"room_version" json:"room_version" toml:"room_version" yaml:"room_version"`
	CreatedAt      time.Time  `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	CreateEventNid null.Int64 `boil:"create_event_nid" json:"create_event_nid,omitempty" toml:"create_event_nid" yaml:"create_event_nid,omitempty"`
	Visibility     string     `boil:"visibility" json:"visibility" toml:"visibility" yaml:"visibility"`

	R *roomR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L roomL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var RoomColumns = struct {
	RoomNid        string
	TenantID       string
	RoomID         string
	RoomVersion    string
	CreatedAt      string
	CreateEventNid string
	Visibility     string
}{
	RoomNid:        "room_nid",
	TenantID:       "tenant_id",
	RoomID:         "room_id",
	RoomVersion:    "room_version",
	CreatedAt:      "created_at",
	CreateEventNid: "create_event_nid",
	Visibility:     "visibility",
}

var RoomTableColumns = struct {
	RoomNid        string
	TenantID       string
	RoomID         string
	RoomVersion    string
	CreatedAt      string
	CreateEventNid string
	Visibility     string
}{
	RoomNid:        "rooms.room_nid",
	TenantID:       "rooms.tenant_id",
	RoomID:         "rooms.room_id",
	RoomVersion:    "rooms.room_version",
	CreatedAt:      "rooms.created_at",
	CreateEventNid: "rooms.create_event_nid",
	Visibility:     "rooms.visibility",
}

// Generated where

var RoomWhere = struct {
	RoomNid        whereHelperint64
	TenantID       whereHelperstring
	RoomID         whereHelperstring
	RoomVersion    whereHelperstring
	CreatedAt      whereHelpertime_Time
	CreateEventNid whereHelpernull_Int64
	Visibility     whereHelperstring
}{
	RoomNid:        whereHelperint64{field: "\"rooms\".\"room_nid\""},
	TenantID:       whereHelperstring{field: "\"rooms\".\"tenant_id\""},
	RoomID:         whereHelperstring{field: "\"rooms\".\"room_id\""},
	RoomVersion:    whereHelperstring{field: "\"rooms\".\"room_version\""},
	CreatedAt:      whereHelpertime_Time{field: "\"rooms\".\"created_at\""},
	CreateEventNid: whereHelpernull_Int64{field: "\"rooms\".\"create_event_nid\""},
	Visibility:     whereHelperstring{field: "\"rooms\".\"visibility\""},
}

// RoomRels is where relationship names are stored.
var RoomRels = struct {
	CreateEventNidEvent    string
	Tenant                 string
	RoomNidEventAuthEdges  string
	RoomNidEventPrevEdges  string
	RoomNidEvents          string
	RoomNidRoomAliases     string
	EventNidEvents         string
	RoomNidRoomMemberships string
	RoomNidStateBlocks     string
	RoomNidStateSnapshots  string
}{
	CreateEventNidEvent:    "CreateEventNidEvent",
	Tenant:                 "Tenant",
	RoomNidEventAuthEdges:  "RoomNidEventAuthEdges",
	RoomNidEventPrevEdges:  "RoomNidEventPrevEdges",
	RoomNidEvents:          "RoomNidEvents",
	RoomNidRoomAliases:     "RoomNidRoomAliases",
	EventNidEvents:         "EventNidEvents",
	RoomNidRoomMemberships: "RoomNidRoomMemberships",
	RoomNidStateBlocks:     "RoomNidStateBlocks",
	RoomNidStateSnapshots:  "RoomNidStateSnapshots",
}

// roomR is where relationships are stored.
type roomR struct {
	CreateEventNidEvent    *Event              `boil:"CreateEventNidEvent" json:"CreateEventNidEvent" toml:"CreateEventNidEvent" yaml:"CreateEventNidEvent"`
	Tenant                 *Tenant             `boil:"Tenant" json:"Tenant" toml:"Tenant" yaml:"Tenant"`
	RoomNidEventAuthEdges  EventAuthEdgeSlice  `boil:"RoomNidEventAuthEdges" json:"RoomNidEventAuthEdges" toml:"RoomNidEventAuthEdges" yaml:"RoomNidEventAuthEdges"`
	RoomNidEventPrevEdges  EventPrevEdgeSlice  `boil:"RoomNidEventPrevEdges" json:"RoomNidEventPrevEdges" toml:"RoomNidEventPrevEdges" yaml:"RoomNidEventPrevEdges"`
	RoomNidEvents          EventSlice          `boil:"RoomNidEvents" json:"RoomNidEvents" toml:"RoomNidEvents" yaml:"RoomNidEvents"`
	RoomNidRoomAliases     RoomAliasSlice      `boil:"RoomNidRoomAliases" json:"RoomNidRoomAliases" toml:"RoomNidRoomAliases" yaml:"RoomNidRoomAliases"`
	EventNidEvents         EventSlice          `boil:"EventNidEvents" json:"EventNidEvents" toml:"EventNidEvents" yaml:"EventNidEvents"`
	RoomNidRoomMemberships RoomMembershipSlice `boil:"RoomNidRoomMemberships" json:"RoomNidRoomMemberships" toml:"RoomNidRoomMemberships" yaml:"RoomNidRoomMemberships"`
	RoomNidStateBlocks     StateBlockSlice     `boil:"RoomNidStateBlocks" json:"RoomNidStateBlocks" toml:"RoomNidStateBlocks" yaml:"RoomNidStateBlocks"`
	RoomNidStateSnapshots  StateSnapshotSlice  `boil:"RoomNidStateSnapshots" json:"RoomNidStateSnapshots" toml:"RoomNidStateSnapshots" yaml:"RoomNidStateSnapshots"`
}

// NewStruct creates a new relationship struct
func (*roomR) NewStruct() *roomR {
	return &roomR{}
}

func (o *Room) GetCreateEventNidEvent() *Event {
	if o == nil {
		return nil
	}

	return o.R.GetCreateEventNidEvent()
}

func (r *roomR) GetCreateEventNidEvent() *Event {
	if r == nil {
		return nil
	}

	return r.CreateEventNidEvent
}

func (o *Room) GetTenant() *Tenant {
	if o == nil {
		return nil
	}

	return o.R.GetTenant()
}

func (r *roomR) GetTenant() *Tenant {
	if r == nil {
		return nil
	}

	return r.Tenant
}

func (o *Room) GetRoomNidEventAuthEdges() EventAuthEdgeSlice {
	if o == nil {
		return nil
	}

	return o.R.GetRoomNidEventAuthEdges()
}

func (r *roomR) GetRoomNidEventAuthEdges() EventAuthEdgeSlice {
	if r == nil {
		return nil
	}

	return r.RoomNidEventAuthEdges
}

func (o *Room) GetRoomNidEventPrevEdges() EventPrevEdgeSlice {
	if o == nil {
		return nil
	}

	return o.R.GetRoomNidEventPrevEdges()
}

func (r *roomR) GetRoomNidEventPrevEdges() EventPrevEdgeSlice {
	if r == nil {
		return nil
	}

	return r.RoomNidEventPrevEdges
}

func (o *Room) GetRoomNidEvents() EventSlice {
	if o == nil {
		return nil
	}

	return o.R.GetRoomNidEvents()
}

func (r *roomR) GetRoomNidEvents() EventSlice {
	if r == nil {
		return nil
	}

	return r.RoomNidEvents
}

func (o *Room) GetRoomNidRoomAliases() RoomAliasSlice {
	if o == nil {
		return nil
	}

	return o.R.GetRoomNidRoomAliases()
}

func (r *roomR) GetRoomNidRoomAliases() RoomAliasSlice {
	if r == nil {
		return nil
	}

	return r.RoomNidRoomAliases
}

func (o *Room) GetEventNidEvents() EventSlice {
	if o == nil {
		return nil
	}

	return o.R.GetEventNidEvents()
}

func (r *roomR) GetEventNidEvents() EventSlice {
	if r == nil {
		return nil
	}

	return r.EventNidEvents
}

func (o *Room) GetRoomNidRoomMemberships() RoomMembershipSlice {
	if o == nil {
		return nil
	}

	return o.R.GetRoomNidRoomMemberships()
}

func (r *roomR) GetRoomNidRoomMemberships() RoomMembershipSlice {
	if r == nil {
		return nil
	}

	return r.RoomNidRoomMemberships
}

func (o *Room) GetRoomNidStateBlocks() StateBlockSlice {
	if o == nil {
		return nil
	}

	return o.R.GetRoomNidStateBlocks()
}

func (r *roomR) GetRoomNidStateBlocks() StateBlockSlice {
	if r == nil {
		return nil
	}

	return r.RoomNidStateBlocks
}

func (o *Room) GetRoomNidStateSnapshots() StateSnapshotSlice {
	if o == nil {
		return nil
	}

	return o.R.GetRoomNidStateSnapshots()
}

func (r *roomR) GetRoomNidStateSnapshots() StateSnapshotSlice {
	if r == nil {
		return nil
	}

	return r.RoomNidStateSnapshots
}

// roomL is where Load methods for each relationship are stored.
type roomL struct{}

var (
	roomAllColumns            = []string{"room_nid", "tenant_id", "room_id", "room_version", "created_at", "create_event_nid", "visibility"}
	roomColumnsWithoutDefault = []string{"tenant_id", "room_id", "room_version"}
	roomColumnsWithDefault    = []string{"room_nid", "created_at", "create_event_nid", "visibility"}
	roomPrimaryKeyColumns     = []string{"room_nid"}
	roomGeneratedColumns      = []string{}
)

type (
	// RoomSlice is an alias for a slice of pointers to Room.
	// This should almost always be used instead of []Room.
	RoomSlice []*Room
	// RoomHook is the signature for custom Room hook methods
	RoomHook func(context.Context, boil.ContextExecutor, *Room) error

	roomQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	roomType                 = reflect.TypeOf(&Room{})
	roomMapping              = queries.MakeStructMapping(roomType)
	roomPrimaryKeyMapping, _ = queries.BindMapping(roomType, roomMapping, roomPrimaryKeyColumns)
	roomInsertCacheMut       sync.RWMutex
	roomInsertCache          = make(map[string]insertCache)
	roomUpdateCacheMut       sync.RWMutex
	roomUpdateCache          = make(map[string]updateCache)
	roomUpsertCacheMut       sync.RWMutex
	roomUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var roomAfterSelectMu sync.Mutex
var roomAfterSelectHooks []RoomHook

var roomBeforeInsertMu sync.Mutex
var roomBeforeInsertHooks []RoomHook
var roomAfterInsertMu sync.Mutex
var roomAfterInsertHooks []RoomHook

var roomBeforeUpdateMu sync.Mutex
var roomBeforeUpdateHooks []RoomHook
var roomAfterUpdateMu sync.Mutex
var roomAfterUpdateHooks []RoomHook

var roomBeforeDeleteMu sync.Mutex
var roomBeforeDeleteHooks []RoomHook
var roomAfterDeleteMu sync.Mutex
var roomAfterDeleteHooks []RoomHook

var roomBeforeUpsertMu sync.Mutex
var roomBeforeUpsertHooks []RoomHook
var roomAfterUpsertMu sync.Mutex
var roomAfterUpsertHooks []RoomHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Room) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range roomAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Room) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range roomBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Room) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range roomAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Room) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range roomBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Room) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range roomAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Room) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range roomBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Room) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range roomAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Room) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range roomBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Room) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range roomAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddRoomHook registers your hook function for all future operations.
func AddRoomHook(hookPoint boil.HookPoint, roomHook RoomHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		roomAfterSelectMu.Lock()
		roomAfterSelectHooks = append(roomAfterSelectHooks, roomHook)
		roomAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		roomBeforeInsertMu.Lock()
		roomBeforeInsertHooks = append(roomBeforeInsertHooks, roomHook)
		roomBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		roomAfterInsertMu.Lock()
		roomAfterInsertHooks = append(roomAfterInsertHooks, roomHook)
		roomAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		roomBeforeUpdateMu.Lock()
		roomBeforeUpdateHooks = append(roomBeforeUpdateHooks, roomHook)
		roomBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		roomAfterUpdateMu.Lock()
		roomAfterUpdateHooks = append(roomAfterUpdateHooks, roomHook)
		roomAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		roomBeforeDeleteMu.Lock()
		roomBeforeDeleteHooks = append(roomBeforeDeleteHooks, roomHook)
		roomBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		roomAfterDeleteMu.Lock()
		roomAfterDeleteHooks = append(roomAfterDeleteHooks, roomHook)
		roomAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		roomBeforeUpsertMu.Lock()
		roomBeforeUpsertHooks = append(roomBeforeUpsertHooks, roomHook)
		roomBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		roomAfterUpsertMu.Lock()
		roomAfterUpsertHooks = append(roomAfterUpsertHooks, roomHook)
		roomAfterUpsertMu.Unlock()
	}
}

// One returns a single room record from the query.
func (q roomQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Room, error) {
	o := &Room{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: failed to execute a one query for rooms")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Room records from the query.
func (q roomQuery) All(ctx context.Context, exec boil.ContextExecutor) (RoomSlice, error) {
	var o []*Room

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbpostgres: failed to assign all query results to Room slice")
	}

	if len(roomAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Room records in the query.
func (q roomQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to count rooms rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q roomQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: failed to check if rooms exists")
	}

	return count > 0, nil
}

// CreateEventNidEvent pointed to by the foreign key.
func (o *Room) CreateEventNidEvent(mods ...qm.QueryMod) eventQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"event_nid\" = ?", o.CreateEventNid),
	}

	queryMods = append(queryMods, mods...)

	return Events(queryMods...)
}

// Tenant pointed to by the foreign key.
func (o *Room) Tenant(mods ...qm.QueryMod) tenantQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.TenantID),
	}

	queryMods = append(queryMods, mods...)

	return Tenants(queryMods...)
}

// RoomNidEventAuthEdges retrieves all the event_auth_edge's EventAuthEdges with an executor via room_nid column.
func (o *Room) RoomNidEventAuthEdges(mods ...qm.QueryMod) eventAuthEdgeQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"event_auth_edges\".\"room_nid\"=?", o.RoomNid),
	)

	return EventAuthEdges(queryMods...)
}

// RoomNidEventPrevEdges retrieves all the event_prev_edge's EventPrevEdges with an executor via room_nid column.
func (o *Room) RoomNidEventPrevEdges(mods ...qm.QueryMod) eventPrevEdgeQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"event_prev_edges\".\"room_nid\"=?", o.RoomNid),
	)

	return EventPrevEdges(queryMods...)
}

// RoomNidEvents retrieves all the event's Events with an executor via room_nid column.
func (o *Room) RoomNidEvents(mods ...qm.QueryMod) eventQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"events\".\"room_nid\"=?", o.RoomNid),
	)

	return Events(queryMods...)
}

// RoomNidRoomAliases retrieves all the room_alias's RoomAliases with an executor via room_nid column.
func (o *Room) RoomNidRoomAliases(mods ...qm.QueryMod) roomAliasQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"room_aliases\".\"room_nid\"=?", o.RoomNid),
	)

	return RoomAliases(queryMods...)
}

// EventNidEvents retrieves all the event's Events with an executor via event_nid column.
func (o *Room) EventNidEvents(mods ...qm.QueryMod) eventQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.InnerJoin("\"room_extremities\" on \"events\".\"event_nid\" = \"room_extremities\".\"event_nid\""),
		qm.Where("\"room_extremities\".\"room_nid\"=?", o.RoomNid),
	)

	return Events(queryMods...)
}

// RoomNidRoomMemberships retrieves all the room_membership's RoomMemberships with an executor via room_nid column.
func (o *Room) RoomNidRoomMemberships(mods ...qm.QueryMod) roomMembershipQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"room_memberships\".\"room_nid\"=?", o.RoomNid),
	)

	return RoomMemberships(queryMods...)
}

// RoomNidStateBlocks retrieves all the state_block's StateBlocks with an executor via room_nid column.
func (o *Room) RoomNidStateBlocks(mods ...qm.QueryMod) stateBlockQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"state_blocks\".\"room_nid\"=?", o.RoomNid),
	)

	return StateBlocks(queryMods...)
}

// RoomNidStateSnapshots retrieves all the state_snapshot's StateSnapshots with an executor via room_nid column.
func (o *Room) RoomNidStateSnapshots(mods ...qm.QueryMod) stateSnapshotQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"state_snapshots\".\"room_nid\"=?", o.RoomNid),
	)

	return StateSnapshots(queryMods...)
}

// LoadCreateEventNidEvent allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (roomL) LoadCreateEventNidEvent(ctx context.Context, e boil.ContextExecutor, singular bool, maybeRoom any, mods queries.Applicator) error {
	var slice []*Room
	var object *Room

	if singular {
		var ok bool
		object, ok = maybeRoom.(*Room)
		if !ok {
			object = new(Room)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeRoom))
			}
		}
	} else {
		s, ok := maybeRoom.(*[]*Room)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeRoom))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &roomR{}
		}
		if !queries.IsNil(object.CreateEventNid) {
			args[object.CreateEventNid] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &roomR{}
			}

			if !queries.IsNil(obj.CreateEventNid) {
				args[obj.CreateEventNid] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`events`),
		qm.WhereIn(`events.event_nid in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Event")
	}

	var resultSlice []*Event
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Event")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for events")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for events")
	}

	if len(eventAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.CreateEventNidEvent = foreign
		if foreign.R == nil {
			foreign.R = &eventR{}
		}
		foreign.R.CreateEventNidRooms = append(foreign.R.CreateEventNidRooms, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.CreateEventNid, foreign.EventNid) {
				local.R.CreateEventNidEvent = foreign
				if foreign.R == nil {
					foreign.R = &eventR{}
				}
				foreign.R.CreateEventNidRooms = append(foreign.R.CreateEventNidRooms, local)
				break
			}
		}
	}

	return nil
}

// LoadTenant allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (roomL) LoadTenant(ctx context.Context, e boil.ContextExecutor, singular bool, maybeRoom any, mods queries.Applicator) error {
	var slice []*Room
	var object *Room

	if singular {
		var ok bool
		object, ok = maybeRoom.(*Room)
		if !ok {
			object = new(Room)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeRoom))
			}
		}
	} else {
		s, ok := maybeRoom.(*[]*Room)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeRoom))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &roomR{}
		}
		args[object.TenantID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &roomR{}
			}

			args[obj.TenantID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tenants`),
		qm.WhereIn(`tenants.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Tenant")
	}

	var resultSlice []*Tenant
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Tenant")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for tenants")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tenants")
	}

	if len(tenantAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Tenant = foreign
		if foreign.R == nil {
			foreign.R = &tenantR{}
		}
		foreign.R.Rooms = append(foreign.R.Rooms, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.TenantID == foreign.ID {
				local.R.Tenant = foreign
				if foreign.R == nil {
					foreign.R = &tenantR{}
				}
				foreign.R.Rooms = append(foreign.R.Rooms, local)
				break
			}
		}
	}

	return nil
}

// LoadRoomNidEventAuthEdges allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (roomL) LoadRoomNidEventAuthEdges(ctx context.Context, e boil.ContextExecutor, singular bool, maybeRoom any, mods queries.Applicator) error {
	var slice []*Room
	var object *Room

	if singular {
		var ok bool
		object, ok = maybeRoom.(*Room)
		if !ok {
			object = new(Room)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeRoom))
			}
		}
	} else {
		s, ok := maybeRoom.(*[]*Room)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeRoom))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &roomR{}
		}
		args[object.RoomNid] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &roomR{}
			}
			args[obj.RoomNid] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`event_auth_edges`),
		qm.WhereIn(`event_auth_edges.room_nid in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load event_auth_edges")
	}

	var resultSlice []*EventAuthEdge
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice event_auth_edges")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on event_auth_edges")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for event_auth_edges")
	}

	if len(eventAuthEdgeAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.RoomNidEventAuthEdges = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &eventAuthEdgeR{}
			}
			foreign.R.RoomNidRoom = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.RoomNid == foreign.RoomNid {
				local.R.RoomNidEventAuthEdges = append(local.R.RoomNidEventAuthEdges, foreign)
				if foreign.R == nil {
					foreign.R = &eventAuthEdgeR{}
				}
				foreign.R.RoomNidRoom = local
				break
			}
		}
	}

	return nil
}

// LoadRoomNidEventPrevEdges allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (roomL) LoadRoomNidEventPrevEdges(ctx context.Context, e boil.ContextExecutor, singular bool, maybeRoom any, mods queries.Applicator) error {
	var slice []*Room
	var object *Room

	if singular {
		var ok bool
		object, ok = maybeRoom.(*Room)
		if !ok {
			object = new(Room)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeRoom))
			}
		}
	} else {
		s, ok := maybeRoom.(*[]*Room)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeRoom))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &roomR{}
		}
		args[object.RoomNid] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &roomR{}
			}
			args[obj.RoomNid] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`event_prev_edges`),
		qm.WhereIn(`event_prev_edges.room_nid in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load event_prev_edges")
	}

	var resultSlice []*EventPrevEdge
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice event_prev_edges")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on event_prev_edges")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for event_prev_edges")
	}

	if len(eventPrevEdgeAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.RoomNidEventPrevEdges = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &eventPrevEdgeR{}
			}
			foreign.R.RoomNidRoom = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.RoomNid == foreign.RoomNid {
				local.R.RoomNidEventPrevEdges = append(local.R.RoomNidEventPrevEdges, foreign)
				if foreign.R == nil {
					foreign.R = &eventPrevEdgeR{}
				}
				foreign.R.RoomNidRoom = local
				break
			}
		}
	}

	return nil
}

// LoadRoomNidEvents allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (roomL) LoadRoomNidEvents(ctx context.Context, e boil.ContextExecutor, singular bool, maybeRoom any, mods queries.Applicator) error {
	var slice []*Room
	var object *Room

	if singular {
		var ok bool
		object, ok = maybeRoom.(*Room)
		if !ok {
			object = new(Room)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeRoom))
			}
		}
	} else {
		s, ok := maybeRoom.(*[]*Room)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeRoom))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &roomR{}
		}
		args[object.RoomNid] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &roomR{}
			}
			args[obj.RoomNid] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`events`),
		qm.WhereIn(`events.room_nid in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load events")
	}

	var resultSlice []*Event
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice events")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on events")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for events")
	}

	if len(eventAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.RoomNidEvents = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &eventR{}
			}
			foreign.R.RoomNidRoom = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.RoomNid == foreign.RoomNid {
				local.R.RoomNidEvents = append(local.R.RoomNidEvents, foreign)
				if foreign.R == nil {
					foreign.R = &eventR{}
				}
				foreign.R.RoomNidRoom = local
				break
			}
		}
	}

	return nil
}

// LoadRoomNidRoomAliases allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (roomL) LoadRoomNidRoomAliases(ctx context.Context, e boil.ContextExecutor, singular bool, maybeRoom any, mods queries.Applicator) error {
	var slice []*Room
	var object *Room

	if singular {
		var ok bool
		object, ok = maybeRoom.(*Room)
		if !ok {
			object = new(Room)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeRoom))
			}
		}
	} else {
		s, ok := maybeRoom.(*[]*Room)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeRoom))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &roomR{}
		}
		args[object.RoomNid] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &roomR{}
			}
			args[obj.RoomNid] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`room_aliases`),
		qm.WhereIn(`room_aliases.room_nid in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load room_aliases")
	}

	var resultSlice []*RoomAlias
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice room_aliases")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on room_aliases")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for room_aliases")
	}

	if len(roomAliasAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.RoomNidRoomAliases = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &roomAliasR{}
			}
			foreign.R.RoomNidRoom = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.RoomNid == foreign.RoomNid {
				local.R.RoomNidRoomAliases = append(local.R.RoomNidRoomAliases, foreign)
				if foreign.R == nil {
					foreign.R = &roomAliasR{}
				}
				foreign.R.RoomNidRoom = local
				break
			}
		}
	}

	return nil
}

// LoadEventNidEvents allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (roomL) LoadEventNidEvents(ctx context.Context, e boil.ContextExecutor, singular bool, maybeRoom any, mods queries.Applicator) error {
	var slice []*Room
	var object *Room

	if singular {
		var ok bool
		object, ok = maybeRoom.(*Room)
		if !ok {
			object = new(Room)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeRoom))
			}
		}
	} else {
		s, ok := maybeRoom.(*[]*Room)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeRoom))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &roomR{}
		}
		args[object.RoomNid] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &roomR{}
			}
			args[obj.RoomNid] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.Select("\"events\".\"event_nid\", \"events\".\"room_nid\", \"events\".\"event_id\", \"events\".\"event_type_nid\", \"events\".\"event_state_key_nid\", \"events\".\"sender\", \"events\".\"sender_is_local\", \"events\".\"depth\", \"events\".\"stream_ordering\", \"events\".\"topological_ordering\", \"events\".\"instance_name\", \"events\".\"origin_server_ts\", \"events\".\"state_snapshot_nid\", \"events\".\"disposition\", \"events\".\"event_json\", \"events\".\"created_at\", \"a\".\"room_nid\""),
		qm.From("\"events\""),
		qm.InnerJoin("\"room_extremities\" as \"a\" on \"events\".\"event_nid\" = \"a\".\"event_nid\""),
		qm.WhereIn("\"a\".\"room_nid\" in ?", argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load events")
	}

	var resultSlice []*Event

	var localJoinCols []int64
	for results.Next() {
		one := new(Event)
		var localJoinCol int64

		err = results.Scan(&one.EventNid, &one.RoomNid, &one.EventID, &one.EventTypeNid, &one.EventStateKeyNid, &one.Sender, &one.SenderIsLocal, &one.Depth, &one.StreamOrdering, &one.TopologicalOrdering, &one.InstanceName, &one.OriginServerTS, &one.StateSnapshotNid, &one.Disposition, &one.EventJSON, &one.CreatedAt, &localJoinCol)
		if err != nil {
			return errors.Wrap(err, "failed to scan eager loaded results for events")
		}
		if err = results.Err(); err != nil {
			return errors.Wrap(err, "failed to plebian-bind eager loaded slice events")
		}

		resultSlice = append(resultSlice, one)
		localJoinCols = append(localJoinCols, localJoinCol)
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on events")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for events")
	}

	if len(eventAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.EventNidEvents = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &eventR{}
			}
			foreign.R.RoomNidRooms = append(foreign.R.RoomNidRooms, object)
		}
		return nil
	}

	for i, foreign := range resultSlice {
		localJoinCol := localJoinCols[i]
		for _, local := range slice {
			if local.RoomNid == localJoinCol {
				local.R.EventNidEvents = append(local.R.EventNidEvents, foreign)
				if foreign.R == nil {
					foreign.R = &eventR{}
				}
				foreign.R.RoomNidRooms = append(foreign.R.RoomNidRooms, local)
				break
			}
		}
	}

	return nil
}

// LoadRoomNidRoomMemberships allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (roomL) LoadRoomNidRoomMemberships(ctx context.Context, e boil.ContextExecutor, singular bool, maybeRoom any, mods queries.Applicator) error {
	var slice []*Room
	var object *Room

	if singular {
		var ok bool
		object, ok = maybeRoom.(*Room)
		if !ok {
			object = new(Room)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeRoom))
			}
		}
	} else {
		s, ok := maybeRoom.(*[]*Room)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeRoom))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &roomR{}
		}
		args[object.RoomNid] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &roomR{}
			}
			args[obj.RoomNid] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`room_memberships`),
		qm.WhereIn(`room_memberships.room_nid in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load room_memberships")
	}

	var resultSlice []*RoomMembership
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice room_memberships")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on room_memberships")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for room_memberships")
	}

	if len(roomMembershipAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.RoomNidRoomMemberships = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &roomMembershipR{}
			}
			foreign.R.RoomNidRoom = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.RoomNid == foreign.RoomNid {
				local.R.RoomNidRoomMemberships = append(local.R.RoomNidRoomMemberships, foreign)
				if foreign.R == nil {
					foreign.R = &roomMembershipR{}
				}
				foreign.R.RoomNidRoom = local
				break
			}
		}
	}

	return nil
}

// LoadRoomNidStateBlocks allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (roomL) LoadRoomNidStateBlocks(ctx context.Context, e boil.ContextExecutor, singular bool, maybeRoom any, mods queries.Applicator) error {
	var slice []*Room
	var object *Room

	if singular {
		var ok bool
		object, ok = maybeRoom.(*Room)
		if !ok {
			object = new(Room)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeRoom))
			}
		}
	} else {
		s, ok := maybeRoom.(*[]*Room)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeRoom))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &roomR{}
		}
		args[object.RoomNid] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &roomR{}
			}
			args[obj.RoomNid] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`state_blocks`),
		qm.WhereIn(`state_blocks.room_nid in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load state_blocks")
	}

	var resultSlice []*StateBlock
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice state_blocks")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on state_blocks")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for state_blocks")
	}

	if len(stateBlockAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.RoomNidStateBlocks = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &stateBlockR{}
			}
			foreign.R.RoomNidRoom = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.RoomNid == foreign.RoomNid {
				local.R.RoomNidStateBlocks = append(local.R.RoomNidStateBlocks, foreign)
				if foreign.R == nil {
					foreign.R = &stateBlockR{}
				}
				foreign.R.RoomNidRoom = local
				break
			}
		}
	}

	return nil
}

// LoadRoomNidStateSnapshots allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (roomL) LoadRoomNidStateSnapshots(ctx context.Context, e boil.ContextExecutor, singular bool, maybeRoom any, mods queries.Applicator) error {
	var slice []*Room
	var object *Room

	if singular {
		var ok bool
		object, ok = maybeRoom.(*Room)
		if !ok {
			object = new(Room)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeRoom))
			}
		}
	} else {
		s, ok := maybeRoom.(*[]*Room)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeRoom))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &roomR{}
		}
		args[object.RoomNid] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &roomR{}
			}
			args[obj.RoomNid] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`state_snapshots`),
		qm.WhereIn(`state_snapshots.room_nid in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load state_snapshots")
	}

	var resultSlice []*StateSnapshot
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice state_snapshots")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on state_snapshots")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for state_snapshots")
	}

	if len(stateSnapshotAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.RoomNidStateSnapshots = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &stateSnapshotR{}
			}
			foreign.R.RoomNidRoom = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.RoomNid == foreign.RoomNid {
				local.R.RoomNidStateSnapshots = append(local.R.RoomNidStateSnapshots, foreign)
				if foreign.R == nil {
					foreign.R = &stateSnapshotR{}
				}
				foreign.R.RoomNidRoom = local
				break
			}
		}
	}

	return nil
}

// SetCreateEventNidEvent of the room to the related item.
// Sets o.R.CreateEventNidEvent to related.
// Adds o to related.R.CreateEventNidRooms.
func (o *Room) SetCreateEventNidEvent(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Event) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"rooms\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"create_event_nid"}),
		strmangle.WhereClause("\"", "\"", 2, roomPrimaryKeyColumns),
	)
	values := []any{related.EventNid, o.RoomNid}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.CreateEventNid, related.EventNid)
	if o.R == nil {
		o.R = &roomR{
			CreateEventNidEvent: related,
		}
	} else {
		o.R.CreateEventNidEvent = related
	}

	if related.R == nil {
		related.R = &eventR{
			CreateEventNidRooms: RoomSlice{o},
		}
	} else {
		related.R.CreateEventNidRooms = append(related.R.CreateEventNidRooms, o)
	}

	return nil
}

// RemoveCreateEventNidEvent relationship.
// Sets o.R.CreateEventNidEvent to nil.
// Removes o from all passed in related items' relationships struct.
func (o *Room) RemoveCreateEventNidEvent(ctx context.Context, exec boil.ContextExecutor, related *Event) error {
	var err error

	queries.SetScanner(&o.CreateEventNid, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("create_event_nid")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.CreateEventNidEvent = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.CreateEventNidRooms {
		if queries.Equal(o.CreateEventNid, ri.CreateEventNid) {
			continue
		}

		ln := len(related.R.CreateEventNidRooms)
		if ln > 1 && i < ln-1 {
			related.R.CreateEventNidRooms[i] = related.R.CreateEventNidRooms[ln-1]
		}
		related.R.CreateEventNidRooms = related.R.CreateEventNidRooms[:ln-1]
		break
	}
	return nil
}

// SetTenant of the room to the related item.
// Sets o.R.Tenant to related.
// Adds o to related.R.Rooms.
func (o *Room) SetTenant(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Tenant) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"rooms\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"tenant_id"}),
		strmangle.WhereClause("\"", "\"", 2, roomPrimaryKeyColumns),
	)
	values := []any{related.ID, o.RoomNid}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.TenantID = related.ID
	if o.R == nil {
		o.R = &roomR{
			Tenant: related,
		}
	} else {
		o.R.Tenant = related
	}

	if related.R == nil {
		related.R = &tenantR{
			Rooms: RoomSlice{o},
		}
	} else {
		related.R.Rooms = append(related.R.Rooms, o)
	}

	return nil
}

// AddRoomNidEventAuthEdges adds the given related objects to the existing relationships
// of the room, optionally inserting them as new records.
// Appends related to o.R.RoomNidEventAuthEdges.
// Sets related.R.RoomNidRoom appropriately.
func (o *Room) AddRoomNidEventAuthEdges(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*EventAuthEdge) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.RoomNid = o.RoomNid
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"event_auth_edges\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"room_nid"}),
				strmangle.WhereClause("\"", "\"", 2, eventAuthEdgePrimaryKeyColumns),
			)
			values := []any{o.RoomNid, rel.ChildNid, rel.ParentID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.RoomNid = o.RoomNid
		}
	}

	if o.R == nil {
		o.R = &roomR{
			RoomNidEventAuthEdges: related,
		}
	} else {
		o.R.RoomNidEventAuthEdges = append(o.R.RoomNidEventAuthEdges, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &eventAuthEdgeR{
				RoomNidRoom: o,
			}
		} else {
			rel.R.RoomNidRoom = o
		}
	}
	return nil
}

// AddRoomNidEventPrevEdges adds the given related objects to the existing relationships
// of the room, optionally inserting them as new records.
// Appends related to o.R.RoomNidEventPrevEdges.
// Sets related.R.RoomNidRoom appropriately.
func (o *Room) AddRoomNidEventPrevEdges(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*EventPrevEdge) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.RoomNid = o.RoomNid
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"event_prev_edges\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"room_nid"}),
				strmangle.WhereClause("\"", "\"", 2, eventPrevEdgePrimaryKeyColumns),
			)
			values := []any{o.RoomNid, rel.ChildNid, rel.ParentID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.RoomNid = o.RoomNid
		}
	}

	if o.R == nil {
		o.R = &roomR{
			RoomNidEventPrevEdges: related,
		}
	} else {
		o.R.RoomNidEventPrevEdges = append(o.R.RoomNidEventPrevEdges, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &eventPrevEdgeR{
				RoomNidRoom: o,
			}
		} else {
			rel.R.RoomNidRoom = o
		}
	}
	return nil
}

// AddRoomNidEvents adds the given related objects to the existing relationships
// of the room, optionally inserting them as new records.
// Appends related to o.R.RoomNidEvents.
// Sets related.R.RoomNidRoom appropriately.
func (o *Room) AddRoomNidEvents(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Event) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.RoomNid = o.RoomNid
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"events\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"room_nid"}),
				strmangle.WhereClause("\"", "\"", 2, eventPrimaryKeyColumns),
			)
			values := []any{o.RoomNid, rel.EventNid}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.RoomNid = o.RoomNid
		}
	}

	if o.R == nil {
		o.R = &roomR{
			RoomNidEvents: related,
		}
	} else {
		o.R.RoomNidEvents = append(o.R.RoomNidEvents, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &eventR{
				RoomNidRoom: o,
			}
		} else {
			rel.R.RoomNidRoom = o
		}
	}
	return nil
}

// AddRoomNidRoomAliases adds the given related objects to the existing relationships
// of the room, optionally inserting them as new records.
// Appends related to o.R.RoomNidRoomAliases.
// Sets related.R.RoomNidRoom appropriately.
func (o *Room) AddRoomNidRoomAliases(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*RoomAlias) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.RoomNid = o.RoomNid
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"room_aliases\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"room_nid"}),
				strmangle.WhereClause("\"", "\"", 2, roomAliasPrimaryKeyColumns),
			)
			values := []any{o.RoomNid, rel.TenantID, rel.Alias}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.RoomNid = o.RoomNid
		}
	}

	if o.R == nil {
		o.R = &roomR{
			RoomNidRoomAliases: related,
		}
	} else {
		o.R.RoomNidRoomAliases = append(o.R.RoomNidRoomAliases, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &roomAliasR{
				RoomNidRoom: o,
			}
		} else {
			rel.R.RoomNidRoom = o
		}
	}
	return nil
}

// AddEventNidEvents adds the given related objects to the existing relationships
// of the room, optionally inserting them as new records.
// Appends related to o.R.EventNidEvents.
// Sets related.R.RoomNidRooms appropriately.
func (o *Room) AddEventNidEvents(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Event) error {
	var err error
	for _, rel := range related {
		if insert {
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		}
	}

	for _, rel := range related {
		query := "insert into \"room_extremities\" (\"room_nid\", \"event_nid\") values ($1, $2)"
		values := []any{o.RoomNid, rel.EventNid}

		if boil.IsDebug(ctx) {
			writer := boil.DebugWriterFrom(ctx)
			fmt.Fprintln(writer, query)
			fmt.Fprintln(writer, values)
		}
		_, err = exec.ExecContext(ctx, query, values...)
		if err != nil {
			return errors.Wrap(err, "failed to insert into join table")
		}
	}
	if o.R == nil {
		o.R = &roomR{
			EventNidEvents: related,
		}
	} else {
		o.R.EventNidEvents = append(o.R.EventNidEvents, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &eventR{
				RoomNidRooms: RoomSlice{o},
			}
		} else {
			rel.R.RoomNidRooms = append(rel.R.RoomNidRooms, o)
		}
	}
	return nil
}

// SetEventNidEvents removes all previously related items of the
// room replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.RoomNidRooms's EventNidEvents accordingly.
// Replaces o.R.EventNidEvents with related.
// Sets related.R.RoomNidRooms's EventNidEvents accordingly.
func (o *Room) SetEventNidEvents(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Event) error {
	query := "delete from \"room_extremities\" where \"room_nid\" = $1"
	values := []any{o.RoomNid}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	removeEventNidEventsFromRoomNidRoomsSlice(o, related)
	if o.R != nil {
		o.R.EventNidEvents = nil
	}

	return o.AddEventNidEvents(ctx, exec, insert, related...)
}

// RemoveEventNidEvents relationships from objects passed in.
// Removes related items from R.EventNidEvents (uses pointer comparison, removal does not keep order)
// Sets related.R.RoomNidRooms.
func (o *Room) RemoveEventNidEvents(ctx context.Context, exec boil.ContextExecutor, related ...*Event) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	query := fmt.Sprintf(
		"delete from \"room_extremities\" where \"room_nid\" = $1 and \"event_nid\" in (%s)",
		strmangle.Placeholders(dialect.UseIndexPlaceholders, len(related), 2, 1),
	)
	values := []any{o.RoomNid}
	for _, rel := range related {
		values = append(values, rel.EventNid)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err = exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}
	removeEventNidEventsFromRoomNidRoomsSlice(o, related)
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.EventNidEvents {
			if rel != ri {
				continue
			}

			ln := len(o.R.EventNidEvents)
			if ln > 1 && i < ln-1 {
				o.R.EventNidEvents[i] = o.R.EventNidEvents[ln-1]
			}
			o.R.EventNidEvents = o.R.EventNidEvents[:ln-1]
			break
		}
	}

	return nil
}

func removeEventNidEventsFromRoomNidRoomsSlice(o *Room, related []*Event) {
	for _, rel := range related {
		if rel.R == nil {
			continue
		}
		for i, ri := range rel.R.RoomNidRooms {
			if o.RoomNid != ri.RoomNid {
				continue
			}

			ln := len(rel.R.RoomNidRooms)
			if ln > 1 && i < ln-1 {
				rel.R.RoomNidRooms[i] = rel.R.RoomNidRooms[ln-1]
			}
			rel.R.RoomNidRooms = rel.R.RoomNidRooms[:ln-1]
			break
		}
	}
}

// AddRoomNidRoomMemberships adds the given related objects to the existing relationships
// of the room, optionally inserting them as new records.
// Appends related to o.R.RoomNidRoomMemberships.
// Sets related.R.RoomNidRoom appropriately.
func (o *Room) AddRoomNidRoomMemberships(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*RoomMembership) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.RoomNid = o.RoomNid
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"room_memberships\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"room_nid"}),
				strmangle.WhereClause("\"", "\"", 2, roomMembershipPrimaryKeyColumns),
			)
			values := []any{o.RoomNid, rel.TenantID, rel.RoomNid, rel.UserID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.RoomNid = o.RoomNid
		}
	}

	if o.R == nil {
		o.R = &roomR{
			RoomNidRoomMemberships: related,
		}
	} else {
		o.R.RoomNidRoomMemberships = append(o.R.RoomNidRoomMemberships, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &roomMembershipR{
				RoomNidRoom: o,
			}
		} else {
			rel.R.RoomNidRoom = o
		}
	}
	return nil
}

// AddRoomNidStateBlocks adds the given related objects to the existing relationships
// of the room, optionally inserting them as new records.
// Appends related to o.R.RoomNidStateBlocks.
// Sets related.R.RoomNidRoom appropriately.
func (o *Room) AddRoomNidStateBlocks(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*StateBlock) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.RoomNid = o.RoomNid
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"state_blocks\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"room_nid"}),
				strmangle.WhereClause("\"", "\"", 2, stateBlockPrimaryKeyColumns),
			)
			values := []any{o.RoomNid, rel.StateBlockNid}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.RoomNid = o.RoomNid
		}
	}

	if o.R == nil {
		o.R = &roomR{
			RoomNidStateBlocks: related,
		}
	} else {
		o.R.RoomNidStateBlocks = append(o.R.RoomNidStateBlocks, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &stateBlockR{
				RoomNidRoom: o,
			}
		} else {
			rel.R.RoomNidRoom = o
		}
	}
	return nil
}

// AddRoomNidStateSnapshots adds the given related objects to the existing relationships
// of the room, optionally inserting them as new records.
// Appends related to o.R.RoomNidStateSnapshots.
// Sets related.R.RoomNidRoom appropriately.
func (o *Room) AddRoomNidStateSnapshots(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*StateSnapshot) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.RoomNid = o.RoomNid
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"state_snapshots\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"room_nid"}),
				strmangle.WhereClause("\"", "\"", 2, stateSnapshotPrimaryKeyColumns),
			)
			values := []any{o.RoomNid, rel.StateSnapshotNid}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.RoomNid = o.RoomNid
		}
	}

	if o.R == nil {
		o.R = &roomR{
			RoomNidStateSnapshots: related,
		}
	} else {
		o.R.RoomNidStateSnapshots = append(o.R.RoomNidStateSnapshots, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &stateSnapshotR{
				RoomNidRoom: o,
			}
		} else {
			rel.R.RoomNidRoom = o
		}
	}
	return nil
}

// Rooms retrieves all the records using an executor.
func Rooms(mods ...qm.QueryMod) roomQuery {
	mods = append(mods, qm.From("\"rooms\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"rooms\".*"})
	}

	return roomQuery{q}
}

// FindRoom retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindRoom(ctx context.Context, exec boil.ContextExecutor, roomNid int64, selectCols ...string) (*Room, error) {
	roomObj := &Room{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"rooms\" where \"room_nid\"=$1", sel,
	)

	q := queries.Raw(query, roomNid)

	err := q.Bind(ctx, exec, roomObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: unable to select from rooms")
	}

	if err = roomObj.doAfterSelectHooks(ctx, exec); err != nil {
		return roomObj, err
	}

	return roomObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Room) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbpostgres: no rooms provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(roomColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	roomInsertCacheMut.RLock()
	cache, cached := roomInsertCache[key]
	roomInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			roomAllColumns,
			roomColumnsWithDefault,
			roomColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(roomType, roomMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(roomType, roomMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"rooms\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"rooms\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to insert into rooms")
	}

	if !cached {
		roomInsertCacheMut.Lock()
		roomInsertCache[key] = cache
		roomInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Room.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Room) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	roomUpdateCacheMut.RLock()
	cache, cached := roomUpdateCache[key]
	roomUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			roomAllColumns,
			roomPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbpostgres: unable to update rooms, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"rooms\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, roomPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(roomType, roomMapping, append(wl, roomPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update rooms row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by update for rooms")
	}

	if !cached {
		roomUpdateCacheMut.Lock()
		roomUpdateCache[key] = cache
		roomUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q roomQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all for rooms")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected for rooms")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o RoomSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbpostgres: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), roomPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"rooms\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, roomPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all in room slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected all in update all room")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Room) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbpostgres: no rooms provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(roomColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	roomUpsertCacheMut.RLock()
	cache, cached := roomUpsertCache[key]
	roomUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			roomAllColumns,
			roomColumnsWithDefault,
			roomColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			roomAllColumns,
			roomPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbpostgres: unable to upsert rooms, could not build update column list")
		}

		ret := strmangle.SetComplement(roomAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(roomPrimaryKeyColumns) == 0 {
				return errors.New("dbpostgres: unable to upsert rooms, could not build conflict column list")
			}

			conflict = make([]string, len(roomPrimaryKeyColumns))
			copy(conflict, roomPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"rooms\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(roomType, roomMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(roomType, roomMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to upsert rooms")
	}

	if !cached {
		roomUpsertCacheMut.Lock()
		roomUpsertCache[key] = cache
		roomUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Room record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Room) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbpostgres: no Room provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), roomPrimaryKeyMapping)
	sql := "DELETE FROM \"rooms\" WHERE \"room_nid\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete from rooms")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by delete for rooms")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q roomQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbpostgres: no roomQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from rooms")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for rooms")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o RoomSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(roomBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), roomPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"rooms\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, roomPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from room slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for rooms")
	}

	if len(roomAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Room) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindRoom(ctx, exec, o.RoomNid)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *RoomSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := RoomSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), roomPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"rooms\".* FROM \"rooms\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, roomPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to reload all in RoomSlice")
	}

	*o = slice

	return nil
}

// RoomExists checks if the Room row exists.
func RoomExists(ctx context.Context, exec boil.ContextExecutor, roomNid int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"rooms\" where \"room_nid\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, roomNid)
	}
	row := exec.QueryRowContext(ctx, sql, roomNid)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: unable to check if rooms exists")
	}

	return exists, nil
}

// Exists checks if the Room row exists.
func (o *Room) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return RoomExists(ctx, exec, o.RoomNid)
}
