// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbpostgres

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// StateSnapshotBlock is an object representing the database table.
type StateSnapshotBlock struct {
	StateSnapshotNid int64 `boil:"state_snapshot_nid" json:"state_snapshot_nid" toml:"state_snapshot_nid" yaml:"state_snapshot_nid"`
	Ordinal          int   `boil:"ordinal" json:"ordinal" toml:"ordinal" yaml:"ordinal"`
	StateBlockNid    int64 `boil:"state_block_nid" json:"state_block_nid" toml:"state_block_nid" yaml:"state_block_nid"`

	R *stateSnapshotBlockR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L stateSnapshotBlockL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var StateSnapshotBlockColumns = struct {
	StateSnapshotNid string
	Ordinal          string
	StateBlockNid    string
}{
	StateSnapshotNid: "state_snapshot_nid",
	Ordinal:          "ordinal",
	StateBlockNid:    "state_block_nid",
}

var StateSnapshotBlockTableColumns = struct {
	StateSnapshotNid string
	Ordinal          string
	StateBlockNid    string
}{
	StateSnapshotNid: "state_snapshot_blocks.state_snapshot_nid",
	Ordinal:          "state_snapshot_blocks.ordinal",
	StateBlockNid:    "state_snapshot_blocks.state_block_nid",
}

// Generated where

var StateSnapshotBlockWhere = struct {
	StateSnapshotNid whereHelperint64
	Ordinal          whereHelperint
	StateBlockNid    whereHelperint64
}{
	StateSnapshotNid: whereHelperint64{field: "\"state_snapshot_blocks\".\"state_snapshot_nid\""},
	Ordinal:          whereHelperint{field: "\"state_snapshot_blocks\".\"ordinal\""},
	StateBlockNid:    whereHelperint64{field: "\"state_snapshot_blocks\".\"state_block_nid\""},
}

// StateSnapshotBlockRels is where relationship names are stored.
var StateSnapshotBlockRels = struct {
	StateBlockNidStateBlock       string
	StateSnapshotNidStateSnapshot string
}{
	StateBlockNidStateBlock:       "StateBlockNidStateBlock",
	StateSnapshotNidStateSnapshot: "StateSnapshotNidStateSnapshot",
}

// stateSnapshotBlockR is where relationships are stored.
type stateSnapshotBlockR struct {
	StateBlockNidStateBlock       *StateBlock    `boil:"StateBlockNidStateBlock" json:"StateBlockNidStateBlock" toml:"StateBlockNidStateBlock" yaml:"StateBlockNidStateBlock"`
	StateSnapshotNidStateSnapshot *StateSnapshot `boil:"StateSnapshotNidStateSnapshot" json:"StateSnapshotNidStateSnapshot" toml:"StateSnapshotNidStateSnapshot" yaml:"StateSnapshotNidStateSnapshot"`
}

// NewStruct creates a new relationship struct
func (*stateSnapshotBlockR) NewStruct() *stateSnapshotBlockR {
	return &stateSnapshotBlockR{}
}

func (o *StateSnapshotBlock) GetStateBlockNidStateBlock() *StateBlock {
	if o == nil {
		return nil
	}

	return o.R.GetStateBlockNidStateBlock()
}

func (r *stateSnapshotBlockR) GetStateBlockNidStateBlock() *StateBlock {
	if r == nil {
		return nil
	}

	return r.StateBlockNidStateBlock
}

func (o *StateSnapshotBlock) GetStateSnapshotNidStateSnapshot() *StateSnapshot {
	if o == nil {
		return nil
	}

	return o.R.GetStateSnapshotNidStateSnapshot()
}

func (r *stateSnapshotBlockR) GetStateSnapshotNidStateSnapshot() *StateSnapshot {
	if r == nil {
		return nil
	}

	return r.StateSnapshotNidStateSnapshot
}

// stateSnapshotBlockL is where Load methods for each relationship are stored.
type stateSnapshotBlockL struct{}

var (
	stateSnapshotBlockAllColumns            = []string{"state_snapshot_nid", "ordinal", "state_block_nid"}
	stateSnapshotBlockColumnsWithoutDefault = []string{"state_snapshot_nid", "ordinal", "state_block_nid"}
	stateSnapshotBlockColumnsWithDefault    = []string{}
	stateSnapshotBlockPrimaryKeyColumns     = []string{"state_snapshot_nid", "ordinal"}
	stateSnapshotBlockGeneratedColumns      = []string{}
)

type (
	// StateSnapshotBlockSlice is an alias for a slice of pointers to StateSnapshotBlock.
	// This should almost always be used instead of []StateSnapshotBlock.
	StateSnapshotBlockSlice []*StateSnapshotBlock
	// StateSnapshotBlockHook is the signature for custom StateSnapshotBlock hook methods
	StateSnapshotBlockHook func(context.Context, boil.ContextExecutor, *StateSnapshotBlock) error

	stateSnapshotBlockQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	stateSnapshotBlockType                 = reflect.TypeOf(&StateSnapshotBlock{})
	stateSnapshotBlockMapping              = queries.MakeStructMapping(stateSnapshotBlockType)
	stateSnapshotBlockPrimaryKeyMapping, _ = queries.BindMapping(stateSnapshotBlockType, stateSnapshotBlockMapping, stateSnapshotBlockPrimaryKeyColumns)
	stateSnapshotBlockInsertCacheMut       sync.RWMutex
	stateSnapshotBlockInsertCache          = make(map[string]insertCache)
	stateSnapshotBlockUpdateCacheMut       sync.RWMutex
	stateSnapshotBlockUpdateCache          = make(map[string]updateCache)
	stateSnapshotBlockUpsertCacheMut       sync.RWMutex
	stateSnapshotBlockUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var stateSnapshotBlockAfterSelectMu sync.Mutex
var stateSnapshotBlockAfterSelectHooks []StateSnapshotBlockHook

var stateSnapshotBlockBeforeInsertMu sync.Mutex
var stateSnapshotBlockBeforeInsertHooks []StateSnapshotBlockHook
var stateSnapshotBlockAfterInsertMu sync.Mutex
var stateSnapshotBlockAfterInsertHooks []StateSnapshotBlockHook

var stateSnapshotBlockBeforeUpdateMu sync.Mutex
var stateSnapshotBlockBeforeUpdateHooks []StateSnapshotBlockHook
var stateSnapshotBlockAfterUpdateMu sync.Mutex
var stateSnapshotBlockAfterUpdateHooks []StateSnapshotBlockHook

var stateSnapshotBlockBeforeDeleteMu sync.Mutex
var stateSnapshotBlockBeforeDeleteHooks []StateSnapshotBlockHook
var stateSnapshotBlockAfterDeleteMu sync.Mutex
var stateSnapshotBlockAfterDeleteHooks []StateSnapshotBlockHook

var stateSnapshotBlockBeforeUpsertMu sync.Mutex
var stateSnapshotBlockBeforeUpsertHooks []StateSnapshotBlockHook
var stateSnapshotBlockAfterUpsertMu sync.Mutex
var stateSnapshotBlockAfterUpsertHooks []StateSnapshotBlockHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *StateSnapshotBlock) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stateSnapshotBlockAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *StateSnapshotBlock) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stateSnapshotBlockBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *StateSnapshotBlock) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stateSnapshotBlockAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *StateSnapshotBlock) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stateSnapshotBlockBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *StateSnapshotBlock) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stateSnapshotBlockAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *StateSnapshotBlock) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stateSnapshotBlockBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *StateSnapshotBlock) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stateSnapshotBlockAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *StateSnapshotBlock) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stateSnapshotBlockBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *StateSnapshotBlock) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range stateSnapshotBlockAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddStateSnapshotBlockHook registers your hook function for all future operations.
func AddStateSnapshotBlockHook(hookPoint boil.HookPoint, stateSnapshotBlockHook StateSnapshotBlockHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		stateSnapshotBlockAfterSelectMu.Lock()
		stateSnapshotBlockAfterSelectHooks = append(stateSnapshotBlockAfterSelectHooks, stateSnapshotBlockHook)
		stateSnapshotBlockAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		stateSnapshotBlockBeforeInsertMu.Lock()
		stateSnapshotBlockBeforeInsertHooks = append(stateSnapshotBlockBeforeInsertHooks, stateSnapshotBlockHook)
		stateSnapshotBlockBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		stateSnapshotBlockAfterInsertMu.Lock()
		stateSnapshotBlockAfterInsertHooks = append(stateSnapshotBlockAfterInsertHooks, stateSnapshotBlockHook)
		stateSnapshotBlockAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		stateSnapshotBlockBeforeUpdateMu.Lock()
		stateSnapshotBlockBeforeUpdateHooks = append(stateSnapshotBlockBeforeUpdateHooks, stateSnapshotBlockHook)
		stateSnapshotBlockBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		stateSnapshotBlockAfterUpdateMu.Lock()
		stateSnapshotBlockAfterUpdateHooks = append(stateSnapshotBlockAfterUpdateHooks, stateSnapshotBlockHook)
		stateSnapshotBlockAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		stateSnapshotBlockBeforeDeleteMu.Lock()
		stateSnapshotBlockBeforeDeleteHooks = append(stateSnapshotBlockBeforeDeleteHooks, stateSnapshotBlockHook)
		stateSnapshotBlockBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		stateSnapshotBlockAfterDeleteMu.Lock()
		stateSnapshotBlockAfterDeleteHooks = append(stateSnapshotBlockAfterDeleteHooks, stateSnapshotBlockHook)
		stateSnapshotBlockAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		stateSnapshotBlockBeforeUpsertMu.Lock()
		stateSnapshotBlockBeforeUpsertHooks = append(stateSnapshotBlockBeforeUpsertHooks, stateSnapshotBlockHook)
		stateSnapshotBlockBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		stateSnapshotBlockAfterUpsertMu.Lock()
		stateSnapshotBlockAfterUpsertHooks = append(stateSnapshotBlockAfterUpsertHooks, stateSnapshotBlockHook)
		stateSnapshotBlockAfterUpsertMu.Unlock()
	}
}

// One returns a single stateSnapshotBlock record from the query.
func (q stateSnapshotBlockQuery) One(ctx context.Context, exec boil.ContextExecutor) (*StateSnapshotBlock, error) {
	o := &StateSnapshotBlock{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: failed to execute a one query for state_snapshot_blocks")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all StateSnapshotBlock records from the query.
func (q stateSnapshotBlockQuery) All(ctx context.Context, exec boil.ContextExecutor) (StateSnapshotBlockSlice, error) {
	var o []*StateSnapshotBlock

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbpostgres: failed to assign all query results to StateSnapshotBlock slice")
	}

	if len(stateSnapshotBlockAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all StateSnapshotBlock records in the query.
func (q stateSnapshotBlockQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to count state_snapshot_blocks rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q stateSnapshotBlockQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: failed to check if state_snapshot_blocks exists")
	}

	return count > 0, nil
}

// StateBlockNidStateBlock pointed to by the foreign key.
func (o *StateSnapshotBlock) StateBlockNidStateBlock(mods ...qm.QueryMod) stateBlockQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"state_block_nid\" = ?", o.StateBlockNid),
	}

	queryMods = append(queryMods, mods...)

	return StateBlocks(queryMods...)
}

// StateSnapshotNidStateSnapshot pointed to by the foreign key.
func (o *StateSnapshotBlock) StateSnapshotNidStateSnapshot(mods ...qm.QueryMod) stateSnapshotQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"state_snapshot_nid\" = ?", o.StateSnapshotNid),
	}

	queryMods = append(queryMods, mods...)

	return StateSnapshots(queryMods...)
}

// LoadStateBlockNidStateBlock allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (stateSnapshotBlockL) LoadStateBlockNidStateBlock(ctx context.Context, e boil.ContextExecutor, singular bool, maybeStateSnapshotBlock any, mods queries.Applicator) error {
	var slice []*StateSnapshotBlock
	var object *StateSnapshotBlock

	if singular {
		var ok bool
		object, ok = maybeStateSnapshotBlock.(*StateSnapshotBlock)
		if !ok {
			object = new(StateSnapshotBlock)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeStateSnapshotBlock)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeStateSnapshotBlock))
			}
		}
	} else {
		s, ok := maybeStateSnapshotBlock.(*[]*StateSnapshotBlock)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeStateSnapshotBlock)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeStateSnapshotBlock))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &stateSnapshotBlockR{}
		}
		args[object.StateBlockNid] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &stateSnapshotBlockR{}
			}

			args[obj.StateBlockNid] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`state_blocks`),
		qm.WhereIn(`state_blocks.state_block_nid in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load StateBlock")
	}

	var resultSlice []*StateBlock
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice StateBlock")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for state_blocks")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for state_blocks")
	}

	if len(stateBlockAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.StateBlockNidStateBlock = foreign
		if foreign.R == nil {
			foreign.R = &stateBlockR{}
		}
		foreign.R.StateBlockNidStateSnapshotBlocks = append(foreign.R.StateBlockNidStateSnapshotBlocks, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.StateBlockNid == foreign.StateBlockNid {
				local.R.StateBlockNidStateBlock = foreign
				if foreign.R == nil {
					foreign.R = &stateBlockR{}
				}
				foreign.R.StateBlockNidStateSnapshotBlocks = append(foreign.R.StateBlockNidStateSnapshotBlocks, local)
				break
			}
		}
	}

	return nil
}

// LoadStateSnapshotNidStateSnapshot allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (stateSnapshotBlockL) LoadStateSnapshotNidStateSnapshot(ctx context.Context, e boil.ContextExecutor, singular bool, maybeStateSnapshotBlock any, mods queries.Applicator) error {
	var slice []*StateSnapshotBlock
	var object *StateSnapshotBlock

	if singular {
		var ok bool
		object, ok = maybeStateSnapshotBlock.(*StateSnapshotBlock)
		if !ok {
			object = new(StateSnapshotBlock)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeStateSnapshotBlock)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeStateSnapshotBlock))
			}
		}
	} else {
		s, ok := maybeStateSnapshotBlock.(*[]*StateSnapshotBlock)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeStateSnapshotBlock)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeStateSnapshotBlock))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &stateSnapshotBlockR{}
		}
		args[object.StateSnapshotNid] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &stateSnapshotBlockR{}
			}

			args[obj.StateSnapshotNid] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`state_snapshots`),
		qm.WhereIn(`state_snapshots.state_snapshot_nid in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load StateSnapshot")
	}

	var resultSlice []*StateSnapshot
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice StateSnapshot")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for state_snapshots")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for state_snapshots")
	}

	if len(stateSnapshotAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.StateSnapshotNidStateSnapshot = foreign
		if foreign.R == nil {
			foreign.R = &stateSnapshotR{}
		}
		foreign.R.StateSnapshotNidStateSnapshotBlocks = append(foreign.R.StateSnapshotNidStateSnapshotBlocks, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.StateSnapshotNid == foreign.StateSnapshotNid {
				local.R.StateSnapshotNidStateSnapshot = foreign
				if foreign.R == nil {
					foreign.R = &stateSnapshotR{}
				}
				foreign.R.StateSnapshotNidStateSnapshotBlocks = append(foreign.R.StateSnapshotNidStateSnapshotBlocks, local)
				break
			}
		}
	}

	return nil
}

// SetStateBlockNidStateBlock of the stateSnapshotBlock to the related item.
// Sets o.R.StateBlockNidStateBlock to related.
// Adds o to related.R.StateBlockNidStateSnapshotBlocks.
func (o *StateSnapshotBlock) SetStateBlockNidStateBlock(ctx context.Context, exec boil.ContextExecutor, insert bool, related *StateBlock) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"state_snapshot_blocks\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"state_block_nid"}),
		strmangle.WhereClause("\"", "\"", 2, stateSnapshotBlockPrimaryKeyColumns),
	)
	values := []any{related.StateBlockNid, o.StateSnapshotNid, o.Ordinal}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.StateBlockNid = related.StateBlockNid
	if o.R == nil {
		o.R = &stateSnapshotBlockR{
			StateBlockNidStateBlock: related,
		}
	} else {
		o.R.StateBlockNidStateBlock = related
	}

	if related.R == nil {
		related.R = &stateBlockR{
			StateBlockNidStateSnapshotBlocks: StateSnapshotBlockSlice{o},
		}
	} else {
		related.R.StateBlockNidStateSnapshotBlocks = append(related.R.StateBlockNidStateSnapshotBlocks, o)
	}

	return nil
}

// SetStateSnapshotNidStateSnapshot of the stateSnapshotBlock to the related item.
// Sets o.R.StateSnapshotNidStateSnapshot to related.
// Adds o to related.R.StateSnapshotNidStateSnapshotBlocks.
func (o *StateSnapshotBlock) SetStateSnapshotNidStateSnapshot(ctx context.Context, exec boil.ContextExecutor, insert bool, related *StateSnapshot) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"state_snapshot_blocks\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"state_snapshot_nid"}),
		strmangle.WhereClause("\"", "\"", 2, stateSnapshotBlockPrimaryKeyColumns),
	)
	values := []any{related.StateSnapshotNid, o.StateSnapshotNid, o.Ordinal}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.StateSnapshotNid = related.StateSnapshotNid
	if o.R == nil {
		o.R = &stateSnapshotBlockR{
			StateSnapshotNidStateSnapshot: related,
		}
	} else {
		o.R.StateSnapshotNidStateSnapshot = related
	}

	if related.R == nil {
		related.R = &stateSnapshotR{
			StateSnapshotNidStateSnapshotBlocks: StateSnapshotBlockSlice{o},
		}
	} else {
		related.R.StateSnapshotNidStateSnapshotBlocks = append(related.R.StateSnapshotNidStateSnapshotBlocks, o)
	}

	return nil
}

// StateSnapshotBlocks retrieves all the records using an executor.
func StateSnapshotBlocks(mods ...qm.QueryMod) stateSnapshotBlockQuery {
	mods = append(mods, qm.From("\"state_snapshot_blocks\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"state_snapshot_blocks\".*"})
	}

	return stateSnapshotBlockQuery{q}
}

// FindStateSnapshotBlock retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindStateSnapshotBlock(ctx context.Context, exec boil.ContextExecutor, stateSnapshotNid int64, ordinal int, selectCols ...string) (*StateSnapshotBlock, error) {
	stateSnapshotBlockObj := &StateSnapshotBlock{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"state_snapshot_blocks\" where \"state_snapshot_nid\"=$1 AND \"ordinal\"=$2", sel,
	)

	q := queries.Raw(query, stateSnapshotNid, ordinal)

	err := q.Bind(ctx, exec, stateSnapshotBlockObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: unable to select from state_snapshot_blocks")
	}

	if err = stateSnapshotBlockObj.doAfterSelectHooks(ctx, exec); err != nil {
		return stateSnapshotBlockObj, err
	}

	return stateSnapshotBlockObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *StateSnapshotBlock) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbpostgres: no state_snapshot_blocks provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(stateSnapshotBlockColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	stateSnapshotBlockInsertCacheMut.RLock()
	cache, cached := stateSnapshotBlockInsertCache[key]
	stateSnapshotBlockInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			stateSnapshotBlockAllColumns,
			stateSnapshotBlockColumnsWithDefault,
			stateSnapshotBlockColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(stateSnapshotBlockType, stateSnapshotBlockMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(stateSnapshotBlockType, stateSnapshotBlockMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"state_snapshot_blocks\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"state_snapshot_blocks\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to insert into state_snapshot_blocks")
	}

	if !cached {
		stateSnapshotBlockInsertCacheMut.Lock()
		stateSnapshotBlockInsertCache[key] = cache
		stateSnapshotBlockInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the StateSnapshotBlock.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *StateSnapshotBlock) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	stateSnapshotBlockUpdateCacheMut.RLock()
	cache, cached := stateSnapshotBlockUpdateCache[key]
	stateSnapshotBlockUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			stateSnapshotBlockAllColumns,
			stateSnapshotBlockPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbpostgres: unable to update state_snapshot_blocks, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"state_snapshot_blocks\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, stateSnapshotBlockPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(stateSnapshotBlockType, stateSnapshotBlockMapping, append(wl, stateSnapshotBlockPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update state_snapshot_blocks row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by update for state_snapshot_blocks")
	}

	if !cached {
		stateSnapshotBlockUpdateCacheMut.Lock()
		stateSnapshotBlockUpdateCache[key] = cache
		stateSnapshotBlockUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q stateSnapshotBlockQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all for state_snapshot_blocks")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected for state_snapshot_blocks")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o StateSnapshotBlockSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbpostgres: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), stateSnapshotBlockPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"state_snapshot_blocks\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, stateSnapshotBlockPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all in stateSnapshotBlock slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected all in update all stateSnapshotBlock")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *StateSnapshotBlock) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbpostgres: no state_snapshot_blocks provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(stateSnapshotBlockColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	stateSnapshotBlockUpsertCacheMut.RLock()
	cache, cached := stateSnapshotBlockUpsertCache[key]
	stateSnapshotBlockUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			stateSnapshotBlockAllColumns,
			stateSnapshotBlockColumnsWithDefault,
			stateSnapshotBlockColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			stateSnapshotBlockAllColumns,
			stateSnapshotBlockPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbpostgres: unable to upsert state_snapshot_blocks, could not build update column list")
		}

		ret := strmangle.SetComplement(stateSnapshotBlockAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(stateSnapshotBlockPrimaryKeyColumns) == 0 {
				return errors.New("dbpostgres: unable to upsert state_snapshot_blocks, could not build conflict column list")
			}

			conflict = make([]string, len(stateSnapshotBlockPrimaryKeyColumns))
			copy(conflict, stateSnapshotBlockPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"state_snapshot_blocks\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(stateSnapshotBlockType, stateSnapshotBlockMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(stateSnapshotBlockType, stateSnapshotBlockMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to upsert state_snapshot_blocks")
	}

	if !cached {
		stateSnapshotBlockUpsertCacheMut.Lock()
		stateSnapshotBlockUpsertCache[key] = cache
		stateSnapshotBlockUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single StateSnapshotBlock record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *StateSnapshotBlock) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbpostgres: no StateSnapshotBlock provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), stateSnapshotBlockPrimaryKeyMapping)
	sql := "DELETE FROM \"state_snapshot_blocks\" WHERE \"state_snapshot_nid\"=$1 AND \"ordinal\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete from state_snapshot_blocks")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by delete for state_snapshot_blocks")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q stateSnapshotBlockQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbpostgres: no stateSnapshotBlockQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from state_snapshot_blocks")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for state_snapshot_blocks")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o StateSnapshotBlockSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(stateSnapshotBlockBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), stateSnapshotBlockPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"state_snapshot_blocks\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, stateSnapshotBlockPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from stateSnapshotBlock slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for state_snapshot_blocks")
	}

	if len(stateSnapshotBlockAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *StateSnapshotBlock) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindStateSnapshotBlock(ctx, exec, o.StateSnapshotNid, o.Ordinal)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *StateSnapshotBlockSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := StateSnapshotBlockSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), stateSnapshotBlockPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"state_snapshot_blocks\".* FROM \"state_snapshot_blocks\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, stateSnapshotBlockPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to reload all in StateSnapshotBlockSlice")
	}

	*o = slice

	return nil
}

// StateSnapshotBlockExists checks if the StateSnapshotBlock row exists.
func StateSnapshotBlockExists(ctx context.Context, exec boil.ContextExecutor, stateSnapshotNid int64, ordinal int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"state_snapshot_blocks\" where \"state_snapshot_nid\"=$1 AND \"ordinal\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, stateSnapshotNid, ordinal)
	}
	row := exec.QueryRowContext(ctx, sql, stateSnapshotNid, ordinal)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: unable to check if state_snapshot_blocks exists")
	}

	return exists, nil
}

// Exists checks if the StateSnapshotBlock row exists.
func (o *StateSnapshotBlock) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return StateSnapshotBlockExists(ctx, exec, o.StateSnapshotNid, o.Ordinal)
}
