// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbpostgres

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// SyncConnectionRoom is an object representing the database table.
type SyncConnectionRoom struct {
	ConnectionNid int64 `boil:"connection_nid" json:"connection_nid" toml:"connection_nid" yaml:"connection_nid"`
	RoomNid       int64 `boil:"room_nid" json:"room_nid" toml:"room_nid" yaml:"room_nid"`
	Pending       bool  `boil:"pending" json:"pending" toml:"pending" yaml:"pending"`
	SentTo        int64 `boil:"sent_to" json:"sent_to" toml:"sent_to" yaml:"sent_to"`
	TimelineLimit int   `boil:"timeline_limit" json:"timeline_limit" toml:"timeline_limit" yaml:"timeline_limit"`
	ConfigNid     int64 `boil:"config_nid" json:"config_nid" toml:"config_nid" yaml:"config_nid"`

	R *syncConnectionRoomR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L syncConnectionRoomL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SyncConnectionRoomColumns = struct {
	ConnectionNid string
	RoomNid       string
	Pending       string
	SentTo        string
	TimelineLimit string
	ConfigNid     string
}{
	ConnectionNid: "connection_nid",
	RoomNid:       "room_nid",
	Pending:       "pending",
	SentTo:        "sent_to",
	TimelineLimit: "timeline_limit",
	ConfigNid:     "config_nid",
}

var SyncConnectionRoomTableColumns = struct {
	ConnectionNid string
	RoomNid       string
	Pending       string
	SentTo        string
	TimelineLimit string
	ConfigNid     string
}{
	ConnectionNid: "sync_connection_rooms.connection_nid",
	RoomNid:       "sync_connection_rooms.room_nid",
	Pending:       "sync_connection_rooms.pending",
	SentTo:        "sync_connection_rooms.sent_to",
	TimelineLimit: "sync_connection_rooms.timeline_limit",
	ConfigNid:     "sync_connection_rooms.config_nid",
}

// Generated where

var SyncConnectionRoomWhere = struct {
	ConnectionNid whereHelperint64
	RoomNid       whereHelperint64
	Pending       whereHelperbool
	SentTo        whereHelperint64
	TimelineLimit whereHelperint
	ConfigNid     whereHelperint64
}{
	ConnectionNid: whereHelperint64{field: "\"sync_connection_rooms\".\"connection_nid\""},
	RoomNid:       whereHelperint64{field: "\"sync_connection_rooms\".\"room_nid\""},
	Pending:       whereHelperbool{field: "\"sync_connection_rooms\".\"pending\""},
	SentTo:        whereHelperint64{field: "\"sync_connection_rooms\".\"sent_to\""},
	TimelineLimit: whereHelperint{field: "\"sync_connection_rooms\".\"timeline_limit\""},
	ConfigNid:     whereHelperint64{field: "\"sync_connection_rooms\".\"config_nid\""},
}

// SyncConnectionRoomRels is where relationship names are stored.
var SyncConnectionRoomRels = struct {
	ConfigNidSyncStateConfig    string
	ConnectionNidSyncConnection string
	RoomNidRoom                 string
}{
	ConfigNidSyncStateConfig:    "ConfigNidSyncStateConfig",
	ConnectionNidSyncConnection: "ConnectionNidSyncConnection",
	RoomNidRoom:                 "RoomNidRoom",
}

// syncConnectionRoomR is where relationships are stored.
type syncConnectionRoomR struct {
	ConfigNidSyncStateConfig    *SyncStateConfig `boil:"ConfigNidSyncStateConfig" json:"ConfigNidSyncStateConfig" toml:"ConfigNidSyncStateConfig" yaml:"ConfigNidSyncStateConfig"`
	ConnectionNidSyncConnection *SyncConnection  `boil:"ConnectionNidSyncConnection" json:"ConnectionNidSyncConnection" toml:"ConnectionNidSyncConnection" yaml:"ConnectionNidSyncConnection"`
	RoomNidRoom                 *Room            `boil:"RoomNidRoom" json:"RoomNidRoom" toml:"RoomNidRoom" yaml:"RoomNidRoom"`
}

// NewStruct creates a new relationship struct
func (*syncConnectionRoomR) NewStruct() *syncConnectionRoomR {
	return &syncConnectionRoomR{}
}

func (o *SyncConnectionRoom) GetConfigNidSyncStateConfig() *SyncStateConfig {
	if o == nil {
		return nil
	}

	return o.R.GetConfigNidSyncStateConfig()
}

func (r *syncConnectionRoomR) GetConfigNidSyncStateConfig() *SyncStateConfig {
	if r == nil {
		return nil
	}

	return r.ConfigNidSyncStateConfig
}

func (o *SyncConnectionRoom) GetConnectionNidSyncConnection() *SyncConnection {
	if o == nil {
		return nil
	}

	return o.R.GetConnectionNidSyncConnection()
}

func (r *syncConnectionRoomR) GetConnectionNidSyncConnection() *SyncConnection {
	if r == nil {
		return nil
	}

	return r.ConnectionNidSyncConnection
}

func (o *SyncConnectionRoom) GetRoomNidRoom() *Room {
	if o == nil {
		return nil
	}

	return o.R.GetRoomNidRoom()
}

func (r *syncConnectionRoomR) GetRoomNidRoom() *Room {
	if r == nil {
		return nil
	}

	return r.RoomNidRoom
}

// syncConnectionRoomL is where Load methods for each relationship are stored.
type syncConnectionRoomL struct{}

var (
	syncConnectionRoomAllColumns            = []string{"connection_nid", "room_nid", "pending", "sent_to", "timeline_limit", "config_nid"}
	syncConnectionRoomColumnsWithoutDefault = []string{"connection_nid", "room_nid", "pending", "sent_to", "timeline_limit", "config_nid"}
	syncConnectionRoomColumnsWithDefault    = []string{}
	syncConnectionRoomPrimaryKeyColumns     = []string{"connection_nid", "room_nid", "pending"}
	syncConnectionRoomGeneratedColumns      = []string{}
)

type (
	// SyncConnectionRoomSlice is an alias for a slice of pointers to SyncConnectionRoom.
	// This should almost always be used instead of []SyncConnectionRoom.
	SyncConnectionRoomSlice []*SyncConnectionRoom
	// SyncConnectionRoomHook is the signature for custom SyncConnectionRoom hook methods
	SyncConnectionRoomHook func(context.Context, boil.ContextExecutor, *SyncConnectionRoom) error

	syncConnectionRoomQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	syncConnectionRoomType                 = reflect.TypeOf(&SyncConnectionRoom{})
	syncConnectionRoomMapping              = queries.MakeStructMapping(syncConnectionRoomType)
	syncConnectionRoomPrimaryKeyMapping, _ = queries.BindMapping(syncConnectionRoomType, syncConnectionRoomMapping, syncConnectionRoomPrimaryKeyColumns)
	syncConnectionRoomInsertCacheMut       sync.RWMutex
	syncConnectionRoomInsertCache          = make(map[string]insertCache)
	syncConnectionRoomUpdateCacheMut       sync.RWMutex
	syncConnectionRoomUpdateCache          = make(map[string]updateCache)
	syncConnectionRoomUpsertCacheMut       sync.RWMutex
	syncConnectionRoomUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var syncConnectionRoomAfterSelectMu sync.Mutex
var syncConnectionRoomAfterSelectHooks []SyncConnectionRoomHook

var syncConnectionRoomBeforeInsertMu sync.Mutex
var syncConnectionRoomBeforeInsertHooks []SyncConnectionRoomHook
var syncConnectionRoomAfterInsertMu sync.Mutex
var syncConnectionRoomAfterInsertHooks []SyncConnectionRoomHook

var syncConnectionRoomBeforeUpdateMu sync.Mutex
var syncConnectionRoomBeforeUpdateHooks []SyncConnectionRoomHook
var syncConnectionRoomAfterUpdateMu sync.Mutex
var syncConnectionRoomAfterUpdateHooks []SyncConnectionRoomHook

var syncConnectionRoomBeforeDeleteMu sync.Mutex
var syncConnectionRoomBeforeDeleteHooks []SyncConnectionRoomHook
var syncConnectionRoomAfterDeleteMu sync.Mutex
var syncConnectionRoomAfterDeleteHooks []SyncConnectionRoomHook

var syncConnectionRoomBeforeUpsertMu sync.Mutex
var syncConnectionRoomBeforeUpsertHooks []SyncConnectionRoomHook
var syncConnectionRoomAfterUpsertMu sync.Mutex
var syncConnectionRoomAfterUpsertHooks []SyncConnectionRoomHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *SyncConnectionRoom) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range syncConnectionRoomAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *SyncConnectionRoom) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range syncConnectionRoomBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *SyncConnectionRoom) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range syncConnectionRoomAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *SyncConnectionRoom) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range syncConnectionRoomBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *SyncConnectionRoom) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range syncConnectionRoomAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *SyncConnectionRoom) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range syncConnectionRoomBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *SyncConnectionRoom) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range syncConnectionRoomAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *SyncConnectionRoom) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range syncConnectionRoomBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *SyncConnectionRoom) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range syncConnectionRoomAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSyncConnectionRoomHook registers your hook function for all future operations.
func AddSyncConnectionRoomHook(hookPoint boil.HookPoint, syncConnectionRoomHook SyncConnectionRoomHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		syncConnectionRoomAfterSelectMu.Lock()
		syncConnectionRoomAfterSelectHooks = append(syncConnectionRoomAfterSelectHooks, syncConnectionRoomHook)
		syncConnectionRoomAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		syncConnectionRoomBeforeInsertMu.Lock()
		syncConnectionRoomBeforeInsertHooks = append(syncConnectionRoomBeforeInsertHooks, syncConnectionRoomHook)
		syncConnectionRoomBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		syncConnectionRoomAfterInsertMu.Lock()
		syncConnectionRoomAfterInsertHooks = append(syncConnectionRoomAfterInsertHooks, syncConnectionRoomHook)
		syncConnectionRoomAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		syncConnectionRoomBeforeUpdateMu.Lock()
		syncConnectionRoomBeforeUpdateHooks = append(syncConnectionRoomBeforeUpdateHooks, syncConnectionRoomHook)
		syncConnectionRoomBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		syncConnectionRoomAfterUpdateMu.Lock()
		syncConnectionRoomAfterUpdateHooks = append(syncConnectionRoomAfterUpdateHooks, syncConnectionRoomHook)
		syncConnectionRoomAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		syncConnectionRoomBeforeDeleteMu.Lock()
		syncConnectionRoomBeforeDeleteHooks = append(syncConnectionRoomBeforeDeleteHooks, syncConnectionRoomHook)
		syncConnectionRoomBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		syncConnectionRoomAfterDeleteMu.Lock()
		syncConnectionRoomAfterDeleteHooks = append(syncConnectionRoomAfterDeleteHooks, syncConnectionRoomHook)
		syncConnectionRoomAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		syncConnectionRoomBeforeUpsertMu.Lock()
		syncConnectionRoomBeforeUpsertHooks = append(syncConnectionRoomBeforeUpsertHooks, syncConnectionRoomHook)
		syncConnectionRoomBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		syncConnectionRoomAfterUpsertMu.Lock()
		syncConnectionRoomAfterUpsertHooks = append(syncConnectionRoomAfterUpsertHooks, syncConnectionRoomHook)
		syncConnectionRoomAfterUpsertMu.Unlock()
	}
}

// One returns a single syncConnectionRoom record from the query.
func (q syncConnectionRoomQuery) One(ctx context.Context, exec boil.ContextExecutor) (*SyncConnectionRoom, error) {
	o := &SyncConnectionRoom{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: failed to execute a one query for sync_connection_rooms")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all SyncConnectionRoom records from the query.
func (q syncConnectionRoomQuery) All(ctx context.Context, exec boil.ContextExecutor) (SyncConnectionRoomSlice, error) {
	var o []*SyncConnectionRoom

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbpostgres: failed to assign all query results to SyncConnectionRoom slice")
	}

	if len(syncConnectionRoomAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all SyncConnectionRoom records in the query.
func (q syncConnectionRoomQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to count sync_connection_rooms rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q syncConnectionRoomQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: failed to check if sync_connection_rooms exists")
	}

	return count > 0, nil
}

// ConfigNidSyncStateConfig pointed to by the foreign key.
func (o *SyncConnectionRoom) ConfigNidSyncStateConfig(mods ...qm.QueryMod) syncStateConfigQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"config_nid\" = ?", o.ConfigNid),
	}

	queryMods = append(queryMods, mods...)

	return SyncStateConfigs(queryMods...)
}

// ConnectionNidSyncConnection pointed to by the foreign key.
func (o *SyncConnectionRoom) ConnectionNidSyncConnection(mods ...qm.QueryMod) syncConnectionQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"connection_nid\" = ?", o.ConnectionNid),
	}

	queryMods = append(queryMods, mods...)

	return SyncConnections(queryMods...)
}

// RoomNidRoom pointed to by the foreign key.
func (o *SyncConnectionRoom) RoomNidRoom(mods ...qm.QueryMod) roomQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"room_nid\" = ?", o.RoomNid),
	}

	queryMods = append(queryMods, mods...)

	return Rooms(queryMods...)
}

// LoadConfigNidSyncStateConfig allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (syncConnectionRoomL) LoadConfigNidSyncStateConfig(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSyncConnectionRoom any, mods queries.Applicator) error {
	var slice []*SyncConnectionRoom
	var object *SyncConnectionRoom

	if singular {
		var ok bool
		object, ok = maybeSyncConnectionRoom.(*SyncConnectionRoom)
		if !ok {
			object = new(SyncConnectionRoom)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSyncConnectionRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSyncConnectionRoom))
			}
		}
	} else {
		s, ok := maybeSyncConnectionRoom.(*[]*SyncConnectionRoom)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSyncConnectionRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSyncConnectionRoom))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &syncConnectionRoomR{}
		}
		args[object.ConfigNid] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &syncConnectionRoomR{}
			}

			args[obj.ConfigNid] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`sync_state_configs`),
		qm.WhereIn(`sync_state_configs.config_nid in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load SyncStateConfig")
	}

	var resultSlice []*SyncStateConfig
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice SyncStateConfig")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for sync_state_configs")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for sync_state_configs")
	}

	if len(syncStateConfigAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ConfigNidSyncStateConfig = foreign
		if foreign.R == nil {
			foreign.R = &syncStateConfigR{}
		}
		foreign.R.ConfigNidSyncConnectionRooms = append(foreign.R.ConfigNidSyncConnectionRooms, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ConfigNid == foreign.ConfigNid {
				local.R.ConfigNidSyncStateConfig = foreign
				if foreign.R == nil {
					foreign.R = &syncStateConfigR{}
				}
				foreign.R.ConfigNidSyncConnectionRooms = append(foreign.R.ConfigNidSyncConnectionRooms, local)
				break
			}
		}
	}

	return nil
}

// LoadConnectionNidSyncConnection allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (syncConnectionRoomL) LoadConnectionNidSyncConnection(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSyncConnectionRoom any, mods queries.Applicator) error {
	var slice []*SyncConnectionRoom
	var object *SyncConnectionRoom

	if singular {
		var ok bool
		object, ok = maybeSyncConnectionRoom.(*SyncConnectionRoom)
		if !ok {
			object = new(SyncConnectionRoom)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSyncConnectionRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSyncConnectionRoom))
			}
		}
	} else {
		s, ok := maybeSyncConnectionRoom.(*[]*SyncConnectionRoom)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSyncConnectionRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSyncConnectionRoom))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &syncConnectionRoomR{}
		}
		args[object.ConnectionNid] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &syncConnectionRoomR{}
			}

			args[obj.ConnectionNid] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`sync_connections`),
		qm.WhereIn(`sync_connections.connection_nid in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load SyncConnection")
	}

	var resultSlice []*SyncConnection
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice SyncConnection")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for sync_connections")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for sync_connections")
	}

	if len(syncConnectionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ConnectionNidSyncConnection = foreign
		if foreign.R == nil {
			foreign.R = &syncConnectionR{}
		}
		foreign.R.ConnectionNidSyncConnectionRooms = append(foreign.R.ConnectionNidSyncConnectionRooms, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ConnectionNid == foreign.ConnectionNid {
				local.R.ConnectionNidSyncConnection = foreign
				if foreign.R == nil {
					foreign.R = &syncConnectionR{}
				}
				foreign.R.ConnectionNidSyncConnectionRooms = append(foreign.R.ConnectionNidSyncConnectionRooms, local)
				break
			}
		}
	}

	return nil
}

// LoadRoomNidRoom allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (syncConnectionRoomL) LoadRoomNidRoom(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSyncConnectionRoom any, mods queries.Applicator) error {
	var slice []*SyncConnectionRoom
	var object *SyncConnectionRoom

	if singular {
		var ok bool
		object, ok = maybeSyncConnectionRoom.(*SyncConnectionRoom)
		if !ok {
			object = new(SyncConnectionRoom)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSyncConnectionRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSyncConnectionRoom))
			}
		}
	} else {
		s, ok := maybeSyncConnectionRoom.(*[]*SyncConnectionRoom)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSyncConnectionRoom)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSyncConnectionRoom))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &syncConnectionRoomR{}
		}
		args[object.RoomNid] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &syncConnectionRoomR{}
			}

			args[obj.RoomNid] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`rooms`),
		qm.WhereIn(`rooms.room_nid in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Room")
	}

	var resultSlice []*Room
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Room")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for rooms")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for rooms")
	}

	if len(roomAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.RoomNidRoom = foreign
		if foreign.R == nil {
			foreign.R = &roomR{}
		}
		foreign.R.RoomNidSyncConnectionRooms = append(foreign.R.RoomNidSyncConnectionRooms, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.RoomNid == foreign.RoomNid {
				local.R.RoomNidRoom = foreign
				if foreign.R == nil {
					foreign.R = &roomR{}
				}
				foreign.R.RoomNidSyncConnectionRooms = append(foreign.R.RoomNidSyncConnectionRooms, local)
				break
			}
		}
	}

	return nil
}

// SetConfigNidSyncStateConfig of the syncConnectionRoom to the related item.
// Sets o.R.ConfigNidSyncStateConfig to related.
// Adds o to related.R.ConfigNidSyncConnectionRooms.
func (o *SyncConnectionRoom) SetConfigNidSyncStateConfig(ctx context.Context, exec boil.ContextExecutor, insert bool, related *SyncStateConfig) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"sync_connection_rooms\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"config_nid"}),
		strmangle.WhereClause("\"", "\"", 2, syncConnectionRoomPrimaryKeyColumns),
	)
	values := []any{related.ConfigNid, o.ConnectionNid, o.RoomNid, o.Pending}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ConfigNid = related.ConfigNid
	if o.R == nil {
		o.R = &syncConnectionRoomR{
			ConfigNidSyncStateConfig: related,
		}
	} else {
		o.R.ConfigNidSyncStateConfig = related
	}

	if related.R == nil {
		related.R = &syncStateConfigR{
			ConfigNidSyncConnectionRooms: SyncConnectionRoomSlice{o},
		}
	} else {
		related.R.ConfigNidSyncConnectionRooms = append(related.R.ConfigNidSyncConnectionRooms, o)
	}

	return nil
}

// SetConnectionNidSyncConnection of the syncConnectionRoom to the related item.
// Sets o.R.ConnectionNidSyncConnection to related.
// Adds o to related.R.ConnectionNidSyncConnectionRooms.
func (o *SyncConnectionRoom) SetConnectionNidSyncConnection(ctx context.Context, exec boil.ContextExecutor, insert bool, related *SyncConnection) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"sync_connection_rooms\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"connection_nid"}),
		strmangle.WhereClause("\"", "\"", 2, syncConnectionRoomPrimaryKeyColumns),
	)
	values := []any{related.ConnectionNid, o.ConnectionNid, o.RoomNid, o.Pending}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ConnectionNid = related.ConnectionNid
	if o.R == nil {
		o.R = &syncConnectionRoomR{
			ConnectionNidSyncConnection: related,
		}
	} else {
		o.R.ConnectionNidSyncConnection = related
	}

	if related.R == nil {
		related.R = &syncConnectionR{
			ConnectionNidSyncConnectionRooms: SyncConnectionRoomSlice{o},
		}
	} else {
		related.R.ConnectionNidSyncConnectionRooms = append(related.R.ConnectionNidSyncConnectionRooms, o)
	}

	return nil
}

// SetRoomNidRoom of the syncConnectionRoom to the related item.
// Sets o.R.RoomNidRoom to related.
// Adds o to related.R.RoomNidSyncConnectionRooms.
func (o *SyncConnectionRoom) SetRoomNidRoom(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Room) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"sync_connection_rooms\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"room_nid"}),
		strmangle.WhereClause("\"", "\"", 2, syncConnectionRoomPrimaryKeyColumns),
	)
	values := []any{related.RoomNid, o.ConnectionNid, o.RoomNid, o.Pending}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.RoomNid = related.RoomNid
	if o.R == nil {
		o.R = &syncConnectionRoomR{
			RoomNidRoom: related,
		}
	} else {
		o.R.RoomNidRoom = related
	}

	if related.R == nil {
		related.R = &roomR{
			RoomNidSyncConnectionRooms: SyncConnectionRoomSlice{o},
		}
	} else {
		related.R.RoomNidSyncConnectionRooms = append(related.R.RoomNidSyncConnectionRooms, o)
	}

	return nil
}

// SyncConnectionRooms retrieves all the records using an executor.
func SyncConnectionRooms(mods ...qm.QueryMod) syncConnectionRoomQuery {
	mods = append(mods, qm.From("\"sync_connection_rooms\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"sync_connection_rooms\".*"})
	}

	return syncConnectionRoomQuery{q}
}

// FindSyncConnectionRoom retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSyncConnectionRoom(ctx context.Context, exec boil.ContextExecutor, connectionNid int64, roomNid int64, pending bool, selectCols ...string) (*SyncConnectionRoom, error) {
	syncConnectionRoomObj := &SyncConnectionRoom{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"sync_connection_rooms\" where \"connection_nid\"=$1 AND \"room_nid\"=$2 AND \"pending\"=$3", sel,
	)

	q := queries.Raw(query, connectionNid, roomNid, pending)

	err := q.Bind(ctx, exec, syncConnectionRoomObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: unable to select from sync_connection_rooms")
	}

	if err = syncConnectionRoomObj.doAfterSelectHooks(ctx, exec); err != nil {
		return syncConnectionRoomObj, err
	}

	return syncConnectionRoomObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *SyncConnectionRoom) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbpostgres: no sync_connection_rooms provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(syncConnectionRoomColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	syncConnectionRoomInsertCacheMut.RLock()
	cache, cached := syncConnectionRoomInsertCache[key]
	syncConnectionRoomInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			syncConnectionRoomAllColumns,
			syncConnectionRoomColumnsWithDefault,
			syncConnectionRoomColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(syncConnectionRoomType, syncConnectionRoomMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(syncConnectionRoomType, syncConnectionRoomMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"sync_connection_rooms\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"sync_connection_rooms\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to insert into sync_connection_rooms")
	}

	if !cached {
		syncConnectionRoomInsertCacheMut.Lock()
		syncConnectionRoomInsertCache[key] = cache
		syncConnectionRoomInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the SyncConnectionRoom.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *SyncConnectionRoom) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	syncConnectionRoomUpdateCacheMut.RLock()
	cache, cached := syncConnectionRoomUpdateCache[key]
	syncConnectionRoomUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			syncConnectionRoomAllColumns,
			syncConnectionRoomPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbpostgres: unable to update sync_connection_rooms, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"sync_connection_rooms\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, syncConnectionRoomPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(syncConnectionRoomType, syncConnectionRoomMapping, append(wl, syncConnectionRoomPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update sync_connection_rooms row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by update for sync_connection_rooms")
	}

	if !cached {
		syncConnectionRoomUpdateCacheMut.Lock()
		syncConnectionRoomUpdateCache[key] = cache
		syncConnectionRoomUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q syncConnectionRoomQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all for sync_connection_rooms")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected for sync_connection_rooms")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SyncConnectionRoomSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbpostgres: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), syncConnectionRoomPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"sync_connection_rooms\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, syncConnectionRoomPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all in syncConnectionRoom slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected all in update all syncConnectionRoom")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *SyncConnectionRoom) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbpostgres: no sync_connection_rooms provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(syncConnectionRoomColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	syncConnectionRoomUpsertCacheMut.RLock()
	cache, cached := syncConnectionRoomUpsertCache[key]
	syncConnectionRoomUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			syncConnectionRoomAllColumns,
			syncConnectionRoomColumnsWithDefault,
			syncConnectionRoomColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			syncConnectionRoomAllColumns,
			syncConnectionRoomPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbpostgres: unable to upsert sync_connection_rooms, could not build update column list")
		}

		ret := strmangle.SetComplement(syncConnectionRoomAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(syncConnectionRoomPrimaryKeyColumns) == 0 {
				return errors.New("dbpostgres: unable to upsert sync_connection_rooms, could not build conflict column list")
			}

			conflict = make([]string, len(syncConnectionRoomPrimaryKeyColumns))
			copy(conflict, syncConnectionRoomPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"sync_connection_rooms\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(syncConnectionRoomType, syncConnectionRoomMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(syncConnectionRoomType, syncConnectionRoomMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to upsert sync_connection_rooms")
	}

	if !cached {
		syncConnectionRoomUpsertCacheMut.Lock()
		syncConnectionRoomUpsertCache[key] = cache
		syncConnectionRoomUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single SyncConnectionRoom record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *SyncConnectionRoom) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbpostgres: no SyncConnectionRoom provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), syncConnectionRoomPrimaryKeyMapping)
	sql := "DELETE FROM \"sync_connection_rooms\" WHERE \"connection_nid\"=$1 AND \"room_nid\"=$2 AND \"pending\"=$3"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete from sync_connection_rooms")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by delete for sync_connection_rooms")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q syncConnectionRoomQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbpostgres: no syncConnectionRoomQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from sync_connection_rooms")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for sync_connection_rooms")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SyncConnectionRoomSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(syncConnectionRoomBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), syncConnectionRoomPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"sync_connection_rooms\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, syncConnectionRoomPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from syncConnectionRoom slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for sync_connection_rooms")
	}

	if len(syncConnectionRoomAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *SyncConnectionRoom) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSyncConnectionRoom(ctx, exec, o.ConnectionNid, o.RoomNid, o.Pending)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SyncConnectionRoomSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SyncConnectionRoomSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), syncConnectionRoomPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"sync_connection_rooms\".* FROM \"sync_connection_rooms\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, syncConnectionRoomPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to reload all in SyncConnectionRoomSlice")
	}

	*o = slice

	return nil
}

// SyncConnectionRoomExists checks if the SyncConnectionRoom row exists.
func SyncConnectionRoomExists(ctx context.Context, exec boil.ContextExecutor, connectionNid int64, roomNid int64, pending bool) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"sync_connection_rooms\" where \"connection_nid\"=$1 AND \"room_nid\"=$2 AND \"pending\"=$3 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, connectionNid, roomNid, pending)
	}
	row := exec.QueryRowContext(ctx, sql, connectionNid, roomNid, pending)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: unable to check if sync_connection_rooms exists")
	}

	return exists, nil
}

// Exists checks if the SyncConnectionRoom row exists.
func (o *SyncConnectionRoom) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return SyncConnectionRoomExists(ctx, exec, o.ConnectionNid, o.RoomNid, o.Pending)
}
