// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbpostgres

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// SyncStateConfig is an object representing the database table.
type SyncStateConfig struct {
	ConfigNid  int64  `boil:"config_nid" json:"config_nid" toml:"config_nid" yaml:"config_nid"`
	ConfigHash []byte `boil:"config_hash" json:"config_hash" toml:"config_hash" yaml:"config_hash"`
	Config     []byte `boil:"config" json:"config" toml:"config" yaml:"config"`

	R *syncStateConfigR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L syncStateConfigL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SyncStateConfigColumns = struct {
	ConfigNid  string
	ConfigHash string
	Config     string
}{
	ConfigNid:  "config_nid",
	ConfigHash: "config_hash",
	Config:     "config",
}

var SyncStateConfigTableColumns = struct {
	ConfigNid  string
	ConfigHash string
	Config     string
}{
	ConfigNid:  "sync_state_configs.config_nid",
	ConfigHash: "sync_state_configs.config_hash",
	Config:     "sync_state_configs.config",
}

// Generated where

var SyncStateConfigWhere = struct {
	ConfigNid  whereHelperint64
	ConfigHash whereHelper__byte
	Config     whereHelper__byte
}{
	ConfigNid:  whereHelperint64{field: "\"sync_state_configs\".\"config_nid\""},
	ConfigHash: whereHelper__byte{field: "\"sync_state_configs\".\"config_hash\""},
	Config:     whereHelper__byte{field: "\"sync_state_configs\".\"config\""},
}

// SyncStateConfigRels is where relationship names are stored.
var SyncStateConfigRels = struct {
	ConfigNidSyncConnectionRooms string
}{
	ConfigNidSyncConnectionRooms: "ConfigNidSyncConnectionRooms",
}

// syncStateConfigR is where relationships are stored.
type syncStateConfigR struct {
	ConfigNidSyncConnectionRooms SyncConnectionRoomSlice `boil:"ConfigNidSyncConnectionRooms" json:"ConfigNidSyncConnectionRooms" toml:"ConfigNidSyncConnectionRooms" yaml:"ConfigNidSyncConnectionRooms"`
}

// NewStruct creates a new relationship struct
func (*syncStateConfigR) NewStruct() *syncStateConfigR {
	return &syncStateConfigR{}
}

func (o *SyncStateConfig) GetConfigNidSyncConnectionRooms() SyncConnectionRoomSlice {
	if o == nil {
		return nil
	}

	return o.R.GetConfigNidSyncConnectionRooms()
}

func (r *syncStateConfigR) GetConfigNidSyncConnectionRooms() SyncConnectionRoomSlice {
	if r == nil {
		return nil
	}

	return r.ConfigNidSyncConnectionRooms
}

// syncStateConfigL is where Load methods for each relationship are stored.
type syncStateConfigL struct{}

var (
	syncStateConfigAllColumns            = []string{"config_nid", "config_hash", "config"}
	syncStateConfigColumnsWithoutDefault = []string{"config_hash", "config"}
	syncStateConfigColumnsWithDefault    = []string{"config_nid"}
	syncStateConfigPrimaryKeyColumns     = []string{"config_nid"}
	syncStateConfigGeneratedColumns      = []string{}
)

type (
	// SyncStateConfigSlice is an alias for a slice of pointers to SyncStateConfig.
	// This should almost always be used instead of []SyncStateConfig.
	SyncStateConfigSlice []*SyncStateConfig
	// SyncStateConfigHook is the signature for custom SyncStateConfig hook methods
	SyncStateConfigHook func(context.Context, boil.ContextExecutor, *SyncStateConfig) error

	syncStateConfigQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	syncStateConfigType                 = reflect.TypeOf(&SyncStateConfig{})
	syncStateConfigMapping              = queries.MakeStructMapping(syncStateConfigType)
	syncStateConfigPrimaryKeyMapping, _ = queries.BindMapping(syncStateConfigType, syncStateConfigMapping, syncStateConfigPrimaryKeyColumns)
	syncStateConfigInsertCacheMut       sync.RWMutex
	syncStateConfigInsertCache          = make(map[string]insertCache)
	syncStateConfigUpdateCacheMut       sync.RWMutex
	syncStateConfigUpdateCache          = make(map[string]updateCache)
	syncStateConfigUpsertCacheMut       sync.RWMutex
	syncStateConfigUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var syncStateConfigAfterSelectMu sync.Mutex
var syncStateConfigAfterSelectHooks []SyncStateConfigHook

var syncStateConfigBeforeInsertMu sync.Mutex
var syncStateConfigBeforeInsertHooks []SyncStateConfigHook
var syncStateConfigAfterInsertMu sync.Mutex
var syncStateConfigAfterInsertHooks []SyncStateConfigHook

var syncStateConfigBeforeUpdateMu sync.Mutex
var syncStateConfigBeforeUpdateHooks []SyncStateConfigHook
var syncStateConfigAfterUpdateMu sync.Mutex
var syncStateConfigAfterUpdateHooks []SyncStateConfigHook

var syncStateConfigBeforeDeleteMu sync.Mutex
var syncStateConfigBeforeDeleteHooks []SyncStateConfigHook
var syncStateConfigAfterDeleteMu sync.Mutex
var syncStateConfigAfterDeleteHooks []SyncStateConfigHook

var syncStateConfigBeforeUpsertMu sync.Mutex
var syncStateConfigBeforeUpsertHooks []SyncStateConfigHook
var syncStateConfigAfterUpsertMu sync.Mutex
var syncStateConfigAfterUpsertHooks []SyncStateConfigHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *SyncStateConfig) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range syncStateConfigAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *SyncStateConfig) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range syncStateConfigBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *SyncStateConfig) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range syncStateConfigAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *SyncStateConfig) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range syncStateConfigBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *SyncStateConfig) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range syncStateConfigAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *SyncStateConfig) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range syncStateConfigBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *SyncStateConfig) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range syncStateConfigAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *SyncStateConfig) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range syncStateConfigBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *SyncStateConfig) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range syncStateConfigAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSyncStateConfigHook registers your hook function for all future operations.
func AddSyncStateConfigHook(hookPoint boil.HookPoint, syncStateConfigHook SyncStateConfigHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		syncStateConfigAfterSelectMu.Lock()
		syncStateConfigAfterSelectHooks = append(syncStateConfigAfterSelectHooks, syncStateConfigHook)
		syncStateConfigAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		syncStateConfigBeforeInsertMu.Lock()
		syncStateConfigBeforeInsertHooks = append(syncStateConfigBeforeInsertHooks, syncStateConfigHook)
		syncStateConfigBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		syncStateConfigAfterInsertMu.Lock()
		syncStateConfigAfterInsertHooks = append(syncStateConfigAfterInsertHooks, syncStateConfigHook)
		syncStateConfigAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		syncStateConfigBeforeUpdateMu.Lock()
		syncStateConfigBeforeUpdateHooks = append(syncStateConfigBeforeUpdateHooks, syncStateConfigHook)
		syncStateConfigBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		syncStateConfigAfterUpdateMu.Lock()
		syncStateConfigAfterUpdateHooks = append(syncStateConfigAfterUpdateHooks, syncStateConfigHook)
		syncStateConfigAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		syncStateConfigBeforeDeleteMu.Lock()
		syncStateConfigBeforeDeleteHooks = append(syncStateConfigBeforeDeleteHooks, syncStateConfigHook)
		syncStateConfigBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		syncStateConfigAfterDeleteMu.Lock()
		syncStateConfigAfterDeleteHooks = append(syncStateConfigAfterDeleteHooks, syncStateConfigHook)
		syncStateConfigAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		syncStateConfigBeforeUpsertMu.Lock()
		syncStateConfigBeforeUpsertHooks = append(syncStateConfigBeforeUpsertHooks, syncStateConfigHook)
		syncStateConfigBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		syncStateConfigAfterUpsertMu.Lock()
		syncStateConfigAfterUpsertHooks = append(syncStateConfigAfterUpsertHooks, syncStateConfigHook)
		syncStateConfigAfterUpsertMu.Unlock()
	}
}

// One returns a single syncStateConfig record from the query.
func (q syncStateConfigQuery) One(ctx context.Context, exec boil.ContextExecutor) (*SyncStateConfig, error) {
	o := &SyncStateConfig{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: failed to execute a one query for sync_state_configs")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all SyncStateConfig records from the query.
func (q syncStateConfigQuery) All(ctx context.Context, exec boil.ContextExecutor) (SyncStateConfigSlice, error) {
	var o []*SyncStateConfig

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbpostgres: failed to assign all query results to SyncStateConfig slice")
	}

	if len(syncStateConfigAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all SyncStateConfig records in the query.
func (q syncStateConfigQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to count sync_state_configs rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q syncStateConfigQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: failed to check if sync_state_configs exists")
	}

	return count > 0, nil
}

// ConfigNidSyncConnectionRooms retrieves all the sync_connection_room's SyncConnectionRooms with an executor via config_nid column.
func (o *SyncStateConfig) ConfigNidSyncConnectionRooms(mods ...qm.QueryMod) syncConnectionRoomQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"sync_connection_rooms\".\"config_nid\"=?", o.ConfigNid),
	)

	return SyncConnectionRooms(queryMods...)
}

// LoadConfigNidSyncConnectionRooms allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (syncStateConfigL) LoadConfigNidSyncConnectionRooms(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSyncStateConfig any, mods queries.Applicator) error {
	var slice []*SyncStateConfig
	var object *SyncStateConfig

	if singular {
		var ok bool
		object, ok = maybeSyncStateConfig.(*SyncStateConfig)
		if !ok {
			object = new(SyncStateConfig)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSyncStateConfig)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSyncStateConfig))
			}
		}
	} else {
		s, ok := maybeSyncStateConfig.(*[]*SyncStateConfig)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSyncStateConfig)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSyncStateConfig))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &syncStateConfigR{}
		}
		args[object.ConfigNid] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &syncStateConfigR{}
			}
			args[obj.ConfigNid] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`sync_connection_rooms`),
		qm.WhereIn(`sync_connection_rooms.config_nid in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load sync_connection_rooms")
	}

	var resultSlice []*SyncConnectionRoom
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice sync_connection_rooms")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on sync_connection_rooms")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for sync_connection_rooms")
	}

	if len(syncConnectionRoomAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ConfigNidSyncConnectionRooms = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &syncConnectionRoomR{}
			}
			foreign.R.ConfigNidSyncStateConfig = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ConfigNid == foreign.ConfigNid {
				local.R.ConfigNidSyncConnectionRooms = append(local.R.ConfigNidSyncConnectionRooms, foreign)
				if foreign.R == nil {
					foreign.R = &syncConnectionRoomR{}
				}
				foreign.R.ConfigNidSyncStateConfig = local
				break
			}
		}
	}

	return nil
}

// AddConfigNidSyncConnectionRooms adds the given related objects to the existing relationships
// of the sync_state_config, optionally inserting them as new records.
// Appends related to o.R.ConfigNidSyncConnectionRooms.
// Sets related.R.ConfigNidSyncStateConfig appropriately.
func (o *SyncStateConfig) AddConfigNidSyncConnectionRooms(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*SyncConnectionRoom) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.ConfigNid = o.ConfigNid
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"sync_connection_rooms\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"config_nid"}),
				strmangle.WhereClause("\"", "\"", 2, syncConnectionRoomPrimaryKeyColumns),
			)
			values := []any{o.ConfigNid, rel.ConnectionNid, rel.RoomNid, rel.Pending}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.ConfigNid = o.ConfigNid
		}
	}

	if o.R == nil {
		o.R = &syncStateConfigR{
			ConfigNidSyncConnectionRooms: related,
		}
	} else {
		o.R.ConfigNidSyncConnectionRooms = append(o.R.ConfigNidSyncConnectionRooms, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &syncConnectionRoomR{
				ConfigNidSyncStateConfig: o,
			}
		} else {
			rel.R.ConfigNidSyncStateConfig = o
		}
	}
	return nil
}

// SyncStateConfigs retrieves all the records using an executor.
func SyncStateConfigs(mods ...qm.QueryMod) syncStateConfigQuery {
	mods = append(mods, qm.From("\"sync_state_configs\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"sync_state_configs\".*"})
	}

	return syncStateConfigQuery{q}
}

// FindSyncStateConfig retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSyncStateConfig(ctx context.Context, exec boil.ContextExecutor, configNid int64, selectCols ...string) (*SyncStateConfig, error) {
	syncStateConfigObj := &SyncStateConfig{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"sync_state_configs\" where \"config_nid\"=$1", sel,
	)

	q := queries.Raw(query, configNid)

	err := q.Bind(ctx, exec, syncStateConfigObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: unable to select from sync_state_configs")
	}

	if err = syncStateConfigObj.doAfterSelectHooks(ctx, exec); err != nil {
		return syncStateConfigObj, err
	}

	return syncStateConfigObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *SyncStateConfig) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbpostgres: no sync_state_configs provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(syncStateConfigColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	syncStateConfigInsertCacheMut.RLock()
	cache, cached := syncStateConfigInsertCache[key]
	syncStateConfigInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			syncStateConfigAllColumns,
			syncStateConfigColumnsWithDefault,
			syncStateConfigColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(syncStateConfigType, syncStateConfigMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(syncStateConfigType, syncStateConfigMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"sync_state_configs\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"sync_state_configs\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to insert into sync_state_configs")
	}

	if !cached {
		syncStateConfigInsertCacheMut.Lock()
		syncStateConfigInsertCache[key] = cache
		syncStateConfigInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the SyncStateConfig.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *SyncStateConfig) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	syncStateConfigUpdateCacheMut.RLock()
	cache, cached := syncStateConfigUpdateCache[key]
	syncStateConfigUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			syncStateConfigAllColumns,
			syncStateConfigPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbpostgres: unable to update sync_state_configs, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"sync_state_configs\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, syncStateConfigPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(syncStateConfigType, syncStateConfigMapping, append(wl, syncStateConfigPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update sync_state_configs row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by update for sync_state_configs")
	}

	if !cached {
		syncStateConfigUpdateCacheMut.Lock()
		syncStateConfigUpdateCache[key] = cache
		syncStateConfigUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q syncStateConfigQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all for sync_state_configs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected for sync_state_configs")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SyncStateConfigSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbpostgres: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), syncStateConfigPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"sync_state_configs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, syncStateConfigPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all in syncStateConfig slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected all in update all syncStateConfig")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *SyncStateConfig) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbpostgres: no sync_state_configs provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(syncStateConfigColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	syncStateConfigUpsertCacheMut.RLock()
	cache, cached := syncStateConfigUpsertCache[key]
	syncStateConfigUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			syncStateConfigAllColumns,
			syncStateConfigColumnsWithDefault,
			syncStateConfigColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			syncStateConfigAllColumns,
			syncStateConfigPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbpostgres: unable to upsert sync_state_configs, could not build update column list")
		}

		ret := strmangle.SetComplement(syncStateConfigAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(syncStateConfigPrimaryKeyColumns) == 0 {
				return errors.New("dbpostgres: unable to upsert sync_state_configs, could not build conflict column list")
			}

			conflict = make([]string, len(syncStateConfigPrimaryKeyColumns))
			copy(conflict, syncStateConfigPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"sync_state_configs\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(syncStateConfigType, syncStateConfigMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(syncStateConfigType, syncStateConfigMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to upsert sync_state_configs")
	}

	if !cached {
		syncStateConfigUpsertCacheMut.Lock()
		syncStateConfigUpsertCache[key] = cache
		syncStateConfigUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single SyncStateConfig record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *SyncStateConfig) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbpostgres: no SyncStateConfig provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), syncStateConfigPrimaryKeyMapping)
	sql := "DELETE FROM \"sync_state_configs\" WHERE \"config_nid\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete from sync_state_configs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by delete for sync_state_configs")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q syncStateConfigQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbpostgres: no syncStateConfigQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from sync_state_configs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for sync_state_configs")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SyncStateConfigSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(syncStateConfigBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), syncStateConfigPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"sync_state_configs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, syncStateConfigPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from syncStateConfig slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for sync_state_configs")
	}

	if len(syncStateConfigAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *SyncStateConfig) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSyncStateConfig(ctx, exec, o.ConfigNid)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SyncStateConfigSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SyncStateConfigSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), syncStateConfigPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"sync_state_configs\".* FROM \"sync_state_configs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, syncStateConfigPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to reload all in SyncStateConfigSlice")
	}

	*o = slice

	return nil
}

// SyncStateConfigExists checks if the SyncStateConfig row exists.
func SyncStateConfigExists(ctx context.Context, exec boil.ContextExecutor, configNid int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"sync_state_configs\" where \"config_nid\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, configNid)
	}
	row := exec.QueryRowContext(ctx, sql, configNid)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: unable to check if sync_state_configs exists")
	}

	return exists, nil
}

// Exists checks if the SyncStateConfig row exists.
func (o *SyncStateConfig) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return SyncStateConfigExists(ctx, exec, o.ConfigNid)
}
