// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbpostgres

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ToDeviceMessage is an object representing the database table.
type ToDeviceMessage struct {
	TenantID  string    `boil:"tenant_id" json:"tenant_id" toml:"tenant_id" yaml:"tenant_id"`
	UserID    string    `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	DeviceID  string    `boil:"device_id" json:"device_id" toml:"device_id" yaml:"device_id"`
	StreamID  int64     `boil:"stream_id" json:"stream_id" toml:"stream_id" yaml:"stream_id"`
	Sender    string    `boil:"sender" json:"sender" toml:"sender" yaml:"sender"`
	EventType string    `boil:"event_type" json:"event_type" toml:"event_type" yaml:"event_type"`
	Content   []byte    `boil:"content" json:"content" toml:"content" yaml:"content"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *toDeviceMessageR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L toDeviceMessageL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ToDeviceMessageColumns = struct {
	TenantID  string
	UserID    string
	DeviceID  string
	StreamID  string
	Sender    string
	EventType string
	Content   string
	CreatedAt string
}{
	TenantID:  "tenant_id",
	UserID:    "user_id",
	DeviceID:  "device_id",
	StreamID:  "stream_id",
	Sender:    "sender",
	EventType: "event_type",
	Content:   "content",
	CreatedAt: "created_at",
}

var ToDeviceMessageTableColumns = struct {
	TenantID  string
	UserID    string
	DeviceID  string
	StreamID  string
	Sender    string
	EventType string
	Content   string
	CreatedAt string
}{
	TenantID:  "to_device_messages.tenant_id",
	UserID:    "to_device_messages.user_id",
	DeviceID:  "to_device_messages.device_id",
	StreamID:  "to_device_messages.stream_id",
	Sender:    "to_device_messages.sender",
	EventType: "to_device_messages.event_type",
	Content:   "to_device_messages.content",
	CreatedAt: "to_device_messages.created_at",
}

// Generated where

var ToDeviceMessageWhere = struct {
	TenantID  whereHelperstring
	UserID    whereHelperstring
	DeviceID  whereHelperstring
	StreamID  whereHelperint64
	Sender    whereHelperstring
	EventType whereHelperstring
	Content   whereHelper__byte
	CreatedAt whereHelpertime_Time
}{
	TenantID:  whereHelperstring{field: "\"to_device_messages\".\"tenant_id\""},
	UserID:    whereHelperstring{field: "\"to_device_messages\".\"user_id\""},
	DeviceID:  whereHelperstring{field: "\"to_device_messages\".\"device_id\""},
	StreamID:  whereHelperint64{field: "\"to_device_messages\".\"stream_id\""},
	Sender:    whereHelperstring{field: "\"to_device_messages\".\"sender\""},
	EventType: whereHelperstring{field: "\"to_device_messages\".\"event_type\""},
	Content:   whereHelper__byte{field: "\"to_device_messages\".\"content\""},
	CreatedAt: whereHelpertime_Time{field: "\"to_device_messages\".\"created_at\""},
}

// ToDeviceMessageRels is where relationship names are stored.
var ToDeviceMessageRels = struct {
}{}

// toDeviceMessageR is where relationships are stored.
type toDeviceMessageR struct {
}

// NewStruct creates a new relationship struct
func (*toDeviceMessageR) NewStruct() *toDeviceMessageR {
	return &toDeviceMessageR{}
}

// toDeviceMessageL is where Load methods for each relationship are stored.
type toDeviceMessageL struct{}

var (
	toDeviceMessageAllColumns            = []string{"tenant_id", "user_id", "device_id", "stream_id", "sender", "event_type", "content", "created_at"}
	toDeviceMessageColumnsWithoutDefault = []string{"tenant_id", "user_id", "device_id", "stream_id", "sender", "event_type", "content"}
	toDeviceMessageColumnsWithDefault    = []string{"created_at"}
	toDeviceMessagePrimaryKeyColumns     = []string{"tenant_id", "user_id", "device_id", "stream_id"}
	toDeviceMessageGeneratedColumns      = []string{}
)

type (
	// ToDeviceMessageSlice is an alias for a slice of pointers to ToDeviceMessage.
	// This should almost always be used instead of []ToDeviceMessage.
	ToDeviceMessageSlice []*ToDeviceMessage
	// ToDeviceMessageHook is the signature for custom ToDeviceMessage hook methods
	ToDeviceMessageHook func(context.Context, boil.ContextExecutor, *ToDeviceMessage) error

	toDeviceMessageQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	toDeviceMessageType                 = reflect.TypeOf(&ToDeviceMessage{})
	toDeviceMessageMapping              = queries.MakeStructMapping(toDeviceMessageType)
	toDeviceMessagePrimaryKeyMapping, _ = queries.BindMapping(toDeviceMessageType, toDeviceMessageMapping, toDeviceMessagePrimaryKeyColumns)
	toDeviceMessageInsertCacheMut       sync.RWMutex
	toDeviceMessageInsertCache          = make(map[string]insertCache)
	toDeviceMessageUpdateCacheMut       sync.RWMutex
	toDeviceMessageUpdateCache          = make(map[string]updateCache)
	toDeviceMessageUpsertCacheMut       sync.RWMutex
	toDeviceMessageUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var toDeviceMessageAfterSelectMu sync.Mutex
var toDeviceMessageAfterSelectHooks []ToDeviceMessageHook

var toDeviceMessageBeforeInsertMu sync.Mutex
var toDeviceMessageBeforeInsertHooks []ToDeviceMessageHook
var toDeviceMessageAfterInsertMu sync.Mutex
var toDeviceMessageAfterInsertHooks []ToDeviceMessageHook

var toDeviceMessageBeforeUpdateMu sync.Mutex
var toDeviceMessageBeforeUpdateHooks []ToDeviceMessageHook
var toDeviceMessageAfterUpdateMu sync.Mutex
var toDeviceMessageAfterUpdateHooks []ToDeviceMessageHook

var toDeviceMessageBeforeDeleteMu sync.Mutex
var toDeviceMessageBeforeDeleteHooks []ToDeviceMessageHook
var toDeviceMessageAfterDeleteMu sync.Mutex
var toDeviceMessageAfterDeleteHooks []ToDeviceMessageHook

var toDeviceMessageBeforeUpsertMu sync.Mutex
var toDeviceMessageBeforeUpsertHooks []ToDeviceMessageHook
var toDeviceMessageAfterUpsertMu sync.Mutex
var toDeviceMessageAfterUpsertHooks []ToDeviceMessageHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ToDeviceMessage) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range toDeviceMessageAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ToDeviceMessage) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range toDeviceMessageBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ToDeviceMessage) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range toDeviceMessageAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ToDeviceMessage) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range toDeviceMessageBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ToDeviceMessage) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range toDeviceMessageAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ToDeviceMessage) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range toDeviceMessageBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ToDeviceMessage) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range toDeviceMessageAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ToDeviceMessage) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range toDeviceMessageBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ToDeviceMessage) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range toDeviceMessageAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddToDeviceMessageHook registers your hook function for all future operations.
func AddToDeviceMessageHook(hookPoint boil.HookPoint, toDeviceMessageHook ToDeviceMessageHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		toDeviceMessageAfterSelectMu.Lock()
		toDeviceMessageAfterSelectHooks = append(toDeviceMessageAfterSelectHooks, toDeviceMessageHook)
		toDeviceMessageAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		toDeviceMessageBeforeInsertMu.Lock()
		toDeviceMessageBeforeInsertHooks = append(toDeviceMessageBeforeInsertHooks, toDeviceMessageHook)
		toDeviceMessageBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		toDeviceMessageAfterInsertMu.Lock()
		toDeviceMessageAfterInsertHooks = append(toDeviceMessageAfterInsertHooks, toDeviceMessageHook)
		toDeviceMessageAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		toDeviceMessageBeforeUpdateMu.Lock()
		toDeviceMessageBeforeUpdateHooks = append(toDeviceMessageBeforeUpdateHooks, toDeviceMessageHook)
		toDeviceMessageBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		toDeviceMessageAfterUpdateMu.Lock()
		toDeviceMessageAfterUpdateHooks = append(toDeviceMessageAfterUpdateHooks, toDeviceMessageHook)
		toDeviceMessageAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		toDeviceMessageBeforeDeleteMu.Lock()
		toDeviceMessageBeforeDeleteHooks = append(toDeviceMessageBeforeDeleteHooks, toDeviceMessageHook)
		toDeviceMessageBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		toDeviceMessageAfterDeleteMu.Lock()
		toDeviceMessageAfterDeleteHooks = append(toDeviceMessageAfterDeleteHooks, toDeviceMessageHook)
		toDeviceMessageAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		toDeviceMessageBeforeUpsertMu.Lock()
		toDeviceMessageBeforeUpsertHooks = append(toDeviceMessageBeforeUpsertHooks, toDeviceMessageHook)
		toDeviceMessageBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		toDeviceMessageAfterUpsertMu.Lock()
		toDeviceMessageAfterUpsertHooks = append(toDeviceMessageAfterUpsertHooks, toDeviceMessageHook)
		toDeviceMessageAfterUpsertMu.Unlock()
	}
}

// One returns a single toDeviceMessage record from the query.
func (q toDeviceMessageQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ToDeviceMessage, error) {
	o := &ToDeviceMessage{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: failed to execute a one query for to_device_messages")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ToDeviceMessage records from the query.
func (q toDeviceMessageQuery) All(ctx context.Context, exec boil.ContextExecutor) (ToDeviceMessageSlice, error) {
	var o []*ToDeviceMessage

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbpostgres: failed to assign all query results to ToDeviceMessage slice")
	}

	if len(toDeviceMessageAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ToDeviceMessage records in the query.
func (q toDeviceMessageQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to count to_device_messages rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q toDeviceMessageQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: failed to check if to_device_messages exists")
	}

	return count > 0, nil
}

// ToDeviceMessages retrieves all the records using an executor.
func ToDeviceMessages(mods ...qm.QueryMod) toDeviceMessageQuery {
	mods = append(mods, qm.From("\"to_device_messages\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"to_device_messages\".*"})
	}

	return toDeviceMessageQuery{q}
}

// FindToDeviceMessage retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindToDeviceMessage(ctx context.Context, exec boil.ContextExecutor, tenantID string, userID string, deviceID string, streamID int64, selectCols ...string) (*ToDeviceMessage, error) {
	toDeviceMessageObj := &ToDeviceMessage{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"to_device_messages\" where \"tenant_id\"=$1 AND \"user_id\"=$2 AND \"device_id\"=$3 AND \"stream_id\"=$4", sel,
	)

	q := queries.Raw(query, tenantID, userID, deviceID, streamID)

	err := q.Bind(ctx, exec, toDeviceMessageObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: unable to select from to_device_messages")
	}

	if err = toDeviceMessageObj.doAfterSelectHooks(ctx, exec); err != nil {
		return toDeviceMessageObj, err
	}

	return toDeviceMessageObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ToDeviceMessage) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbpostgres: no to_device_messages provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(toDeviceMessageColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	toDeviceMessageInsertCacheMut.RLock()
	cache, cached := toDeviceMessageInsertCache[key]
	toDeviceMessageInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			toDeviceMessageAllColumns,
			toDeviceMessageColumnsWithDefault,
			toDeviceMessageColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(toDeviceMessageType, toDeviceMessageMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(toDeviceMessageType, toDeviceMessageMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"to_device_messages\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"to_device_messages\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to insert into to_device_messages")
	}

	if !cached {
		toDeviceMessageInsertCacheMut.Lock()
		toDeviceMessageInsertCache[key] = cache
		toDeviceMessageInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ToDeviceMessage.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ToDeviceMessage) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	toDeviceMessageUpdateCacheMut.RLock()
	cache, cached := toDeviceMessageUpdateCache[key]
	toDeviceMessageUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			toDeviceMessageAllColumns,
			toDeviceMessagePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbpostgres: unable to update to_device_messages, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"to_device_messages\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, toDeviceMessagePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(toDeviceMessageType, toDeviceMessageMapping, append(wl, toDeviceMessagePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update to_device_messages row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by update for to_device_messages")
	}

	if !cached {
		toDeviceMessageUpdateCacheMut.Lock()
		toDeviceMessageUpdateCache[key] = cache
		toDeviceMessageUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q toDeviceMessageQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all for to_device_messages")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected for to_device_messages")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ToDeviceMessageSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbpostgres: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), toDeviceMessagePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"to_device_messages\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, toDeviceMessagePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all in toDeviceMessage slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected all in update all toDeviceMessage")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ToDeviceMessage) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbpostgres: no to_device_messages provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(toDeviceMessageColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	toDeviceMessageUpsertCacheMut.RLock()
	cache, cached := toDeviceMessageUpsertCache[key]
	toDeviceMessageUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			toDeviceMessageAllColumns,
			toDeviceMessageColumnsWithDefault,
			toDeviceMessageColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			toDeviceMessageAllColumns,
			toDeviceMessagePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbpostgres: unable to upsert to_device_messages, could not build update column list")
		}

		ret := strmangle.SetComplement(toDeviceMessageAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(toDeviceMessagePrimaryKeyColumns) == 0 {
				return errors.New("dbpostgres: unable to upsert to_device_messages, could not build conflict column list")
			}

			conflict = make([]string, len(toDeviceMessagePrimaryKeyColumns))
			copy(conflict, toDeviceMessagePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"to_device_messages\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(toDeviceMessageType, toDeviceMessageMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(toDeviceMessageType, toDeviceMessageMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to upsert to_device_messages")
	}

	if !cached {
		toDeviceMessageUpsertCacheMut.Lock()
		toDeviceMessageUpsertCache[key] = cache
		toDeviceMessageUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ToDeviceMessage record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ToDeviceMessage) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbpostgres: no ToDeviceMessage provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), toDeviceMessagePrimaryKeyMapping)
	sql := "DELETE FROM \"to_device_messages\" WHERE \"tenant_id\"=$1 AND \"user_id\"=$2 AND \"device_id\"=$3 AND \"stream_id\"=$4"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete from to_device_messages")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by delete for to_device_messages")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q toDeviceMessageQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbpostgres: no toDeviceMessageQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from to_device_messages")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for to_device_messages")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ToDeviceMessageSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(toDeviceMessageBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), toDeviceMessagePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"to_device_messages\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, toDeviceMessagePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from toDeviceMessage slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for to_device_messages")
	}

	if len(toDeviceMessageAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ToDeviceMessage) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindToDeviceMessage(ctx, exec, o.TenantID, o.UserID, o.DeviceID, o.StreamID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ToDeviceMessageSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ToDeviceMessageSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), toDeviceMessagePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"to_device_messages\".* FROM \"to_device_messages\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, toDeviceMessagePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to reload all in ToDeviceMessageSlice")
	}

	*o = slice

	return nil
}

// ToDeviceMessageExists checks if the ToDeviceMessage row exists.
func ToDeviceMessageExists(ctx context.Context, exec boil.ContextExecutor, tenantID string, userID string, deviceID string, streamID int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"to_device_messages\" where \"tenant_id\"=$1 AND \"user_id\"=$2 AND \"device_id\"=$3 AND \"stream_id\"=$4 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, tenantID, userID, deviceID, streamID)
	}
	row := exec.QueryRowContext(ctx, sql, tenantID, userID, deviceID, streamID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: unable to check if to_device_messages exists")
	}

	return exists, nil
}

// Exists checks if the ToDeviceMessage row exists.
func (o *ToDeviceMessage) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ToDeviceMessageExists(ctx, exec, o.TenantID, o.UserID, o.DeviceID, o.StreamID)
}
