// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbpostgres

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// UserPresence is an object representing the database table.
type UserPresence struct {
	TenantID     string    `boil:"tenant_id" json:"tenant_id" toml:"tenant_id" yaml:"tenant_id"`
	UserID       string    `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	Presence     string    `boil:"presence" json:"presence" toml:"presence" yaml:"presence"`
	StatusMSG    string    `boil:"status_msg" json:"status_msg" toml:"status_msg" yaml:"status_msg"`
	LastActiveAt time.Time `boil:"last_active_at" json:"last_active_at" toml:"last_active_at" yaml:"last_active_at"`
	UpdatedAt    time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *userPresenceR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userPresenceL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserPresenceColumns = struct {
	TenantID     string
	UserID       string
	Presence     string
	StatusMSG    string
	LastActiveAt string
	UpdatedAt    string
}{
	TenantID:     "tenant_id",
	UserID:       "user_id",
	Presence:     "presence",
	StatusMSG:    "status_msg",
	LastActiveAt: "last_active_at",
	UpdatedAt:    "updated_at",
}

var UserPresenceTableColumns = struct {
	TenantID     string
	UserID       string
	Presence     string
	StatusMSG    string
	LastActiveAt string
	UpdatedAt    string
}{
	TenantID:     "user_presence.tenant_id",
	UserID:       "user_presence.user_id",
	Presence:     "user_presence.presence",
	StatusMSG:    "user_presence.status_msg",
	LastActiveAt: "user_presence.last_active_at",
	UpdatedAt:    "user_presence.updated_at",
}

// Generated where

var UserPresenceWhere = struct {
	TenantID     whereHelperstring
	UserID       whereHelperstring
	Presence     whereHelperstring
	StatusMSG    whereHelperstring
	LastActiveAt whereHelpertime_Time
	UpdatedAt    whereHelpertime_Time
}{
	TenantID:     whereHelperstring{field: "\"user_presence\".\"tenant_id\""},
	UserID:       whereHelperstring{field: "\"user_presence\".\"user_id\""},
	Presence:     whereHelperstring{field: "\"user_presence\".\"presence\""},
	StatusMSG:    whereHelperstring{field: "\"user_presence\".\"status_msg\""},
	LastActiveAt: whereHelpertime_Time{field: "\"user_presence\".\"last_active_at\""},
	UpdatedAt:    whereHelpertime_Time{field: "\"user_presence\".\"updated_at\""},
}

// UserPresenceRels is where relationship names are stored.
var UserPresenceRels = struct {
}{}

// userPresenceR is where relationships are stored.
type userPresenceR struct {
}

// NewStruct creates a new relationship struct
func (*userPresenceR) NewStruct() *userPresenceR {
	return &userPresenceR{}
}

// userPresenceL is where Load methods for each relationship are stored.
type userPresenceL struct{}

var (
	userPresenceAllColumns            = []string{"tenant_id", "user_id", "presence", "status_msg", "last_active_at", "updated_at"}
	userPresenceColumnsWithoutDefault = []string{"tenant_id", "user_id", "presence"}
	userPresenceColumnsWithDefault    = []string{"status_msg", "last_active_at", "updated_at"}
	userPresencePrimaryKeyColumns     = []string{"tenant_id", "user_id"}
	userPresenceGeneratedColumns      = []string{}
)

type (
	// UserPresenceSlice is an alias for a slice of pointers to UserPresence.
	// This should almost always be used instead of []UserPresence.
	UserPresenceSlice []*UserPresence
	// UserPresenceHook is the signature for custom UserPresence hook methods
	UserPresenceHook func(context.Context, boil.ContextExecutor, *UserPresence) error

	userPresenceQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userPresenceType                 = reflect.TypeOf(&UserPresence{})
	userPresenceMapping              = queries.MakeStructMapping(userPresenceType)
	userPresencePrimaryKeyMapping, _ = queries.BindMapping(userPresenceType, userPresenceMapping, userPresencePrimaryKeyColumns)
	userPresenceInsertCacheMut       sync.RWMutex
	userPresenceInsertCache          = make(map[string]insertCache)
	userPresenceUpdateCacheMut       sync.RWMutex
	userPresenceUpdateCache          = make(map[string]updateCache)
	userPresenceUpsertCacheMut       sync.RWMutex
	userPresenceUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var userPresenceAfterSelectMu sync.Mutex
var userPresenceAfterSelectHooks []UserPresenceHook

var userPresenceBeforeInsertMu sync.Mutex
var userPresenceBeforeInsertHooks []UserPresenceHook
var userPresenceAfterInsertMu sync.Mutex
var userPresenceAfterInsertHooks []UserPresenceHook

var userPresenceBeforeUpdateMu sync.Mutex
var userPresenceBeforeUpdateHooks []UserPresenceHook
var userPresenceAfterUpdateMu sync.Mutex
var userPresenceAfterUpdateHooks []UserPresenceHook

var userPresenceBeforeDeleteMu sync.Mutex
var userPresenceBeforeDeleteHooks []UserPresenceHook
var userPresenceAfterDeleteMu sync.Mutex
var userPresenceAfterDeleteHooks []UserPresenceHook

var userPresenceBeforeUpsertMu sync.Mutex
var userPresenceBeforeUpsertHooks []UserPresenceHook
var userPresenceAfterUpsertMu sync.Mutex
var userPresenceAfterUpsertHooks []UserPresenceHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserPresence) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userPresenceAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserPresence) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userPresenceBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserPresence) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userPresenceAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserPresence) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userPresenceBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserPresence) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userPresenceAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserPresence) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userPresenceBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserPresence) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userPresenceAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserPresence) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userPresenceBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserPresence) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userPresenceAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserPresenceHook registers your hook function for all future operations.
func AddUserPresenceHook(hookPoint boil.HookPoint, userPresenceHook UserPresenceHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		userPresenceAfterSelectMu.Lock()
		userPresenceAfterSelectHooks = append(userPresenceAfterSelectHooks, userPresenceHook)
		userPresenceAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		userPresenceBeforeInsertMu.Lock()
		userPresenceBeforeInsertHooks = append(userPresenceBeforeInsertHooks, userPresenceHook)
		userPresenceBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		userPresenceAfterInsertMu.Lock()
		userPresenceAfterInsertHooks = append(userPresenceAfterInsertHooks, userPresenceHook)
		userPresenceAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		userPresenceBeforeUpdateMu.Lock()
		userPresenceBeforeUpdateHooks = append(userPresenceBeforeUpdateHooks, userPresenceHook)
		userPresenceBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		userPresenceAfterUpdateMu.Lock()
		userPresenceAfterUpdateHooks = append(userPresenceAfterUpdateHooks, userPresenceHook)
		userPresenceAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		userPresenceBeforeDeleteMu.Lock()
		userPresenceBeforeDeleteHooks = append(userPresenceBeforeDeleteHooks, userPresenceHook)
		userPresenceBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		userPresenceAfterDeleteMu.Lock()
		userPresenceAfterDeleteHooks = append(userPresenceAfterDeleteHooks, userPresenceHook)
		userPresenceAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		userPresenceBeforeUpsertMu.Lock()
		userPresenceBeforeUpsertHooks = append(userPresenceBeforeUpsertHooks, userPresenceHook)
		userPresenceBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		userPresenceAfterUpsertMu.Lock()
		userPresenceAfterUpsertHooks = append(userPresenceAfterUpsertHooks, userPresenceHook)
		userPresenceAfterUpsertMu.Unlock()
	}
}

// One returns a single userPresence record from the query.
func (q userPresenceQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserPresence, error) {
	o := &UserPresence{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: failed to execute a one query for user_presence")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all UserPresence records from the query.
func (q userPresenceQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserPresenceSlice, error) {
	var o []*UserPresence

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbpostgres: failed to assign all query results to UserPresence slice")
	}

	if len(userPresenceAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all UserPresence records in the query.
func (q userPresenceQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to count user_presence rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q userPresenceQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: failed to check if user_presence exists")
	}

	return count > 0, nil
}

// UserPresences retrieves all the records using an executor.
func UserPresences(mods ...qm.QueryMod) userPresenceQuery {
	mods = append(mods, qm.From("\"user_presence\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"user_presence\".*"})
	}

	return userPresenceQuery{q}
}

// FindUserPresence retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserPresence(ctx context.Context, exec boil.ContextExecutor, tenantID string, userID string, selectCols ...string) (*UserPresence, error) {
	userPresenceObj := &UserPresence{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"user_presence\" where \"tenant_id\"=$1 AND \"user_id\"=$2", sel,
	)

	q := queries.Raw(query, tenantID, userID)

	err := q.Bind(ctx, exec, userPresenceObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: unable to select from user_presence")
	}

	if err = userPresenceObj.doAfterSelectHooks(ctx, exec); err != nil {
		return userPresenceObj, err
	}

	return userPresenceObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserPresence) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbpostgres: no user_presence provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userPresenceColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userPresenceInsertCacheMut.RLock()
	cache, cached := userPresenceInsertCache[key]
	userPresenceInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userPresenceAllColumns,
			userPresenceColumnsWithDefault,
			userPresenceColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userPresenceType, userPresenceMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userPresenceType, userPresenceMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"user_presence\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"user_presence\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to insert into user_presence")
	}

	if !cached {
		userPresenceInsertCacheMut.Lock()
		userPresenceInsertCache[key] = cache
		userPresenceInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the UserPresence.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserPresence) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	userPresenceUpdateCacheMut.RLock()
	cache, cached := userPresenceUpdateCache[key]
	userPresenceUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userPresenceAllColumns,
			userPresencePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbpostgres: unable to update user_presence, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"user_presence\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, userPresencePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userPresenceType, userPresenceMapping, append(wl, userPresencePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update user_presence row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by update for user_presence")
	}

	if !cached {
		userPresenceUpdateCacheMut.Lock()
		userPresenceUpdateCache[key] = cache
		userPresenceUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q userPresenceQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all for user_presence")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected for user_presence")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserPresenceSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbpostgres: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userPresencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"user_presence\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, userPresencePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all in userPresence slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected all in update all userPresence")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UserPresence) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbpostgres: no user_presence provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userPresenceColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userPresenceUpsertCacheMut.RLock()
	cache, cached := userPresenceUpsertCache[key]
	userPresenceUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			userPresenceAllColumns,
			userPresenceColumnsWithDefault,
			userPresenceColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			userPresenceAllColumns,
			userPresencePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbpostgres: unable to upsert user_presence, could not build update column list")
		}

		ret := strmangle.SetComplement(userPresenceAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(userPresencePrimaryKeyColumns) == 0 {
				return errors.New("dbpostgres: unable to upsert user_presence, could not build conflict column list")
			}

			conflict = make([]string, len(userPresencePrimaryKeyColumns))
			copy(conflict, userPresencePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"user_presence\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(userPresenceType, userPresenceMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userPresenceType, userPresenceMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to upsert user_presence")
	}

	if !cached {
		userPresenceUpsertCacheMut.Lock()
		userPresenceUpsertCache[key] = cache
		userPresenceUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single UserPresence record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserPresence) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbpostgres: no UserPresence provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userPresencePrimaryKeyMapping)
	sql := "DELETE FROM \"user_presence\" WHERE \"tenant_id\"=$1 AND \"user_id\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete from user_presence")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by delete for user_presence")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q userPresenceQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbpostgres: no userPresenceQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from user_presence")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for user_presence")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserPresenceSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(userPresenceBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userPresencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"user_presence\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userPresencePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from userPresence slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for user_presence")
	}

	if len(userPresenceAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserPresence) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserPresence(ctx, exec, o.TenantID, o.UserID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserPresenceSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserPresenceSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userPresencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"user_presence\".* FROM \"user_presence\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userPresencePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to reload all in UserPresenceSlice")
	}

	*o = slice

	return nil
}

// UserPresenceExists checks if the UserPresence row exists.
func UserPresenceExists(ctx context.Context, exec boil.ContextExecutor, tenantID string, userID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"user_presence\" where \"tenant_id\"=$1 AND \"user_id\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, tenantID, userID)
	}
	row := exec.QueryRowContext(ctx, sql, tenantID, userID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: unable to check if user_presence exists")
	}

	return exists, nil
}

// Exists checks if the UserPresence row exists.
func (o *UserPresence) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return UserPresenceExists(ctx, exec, o.TenantID, o.UserID)
}
