// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"context"
	"github.com/thelemail/thaumaste/internal/config"
)

// Injectors from wire.go:

func InitializeServe(ctx context.Context, cfg config.Config) (*ServeRuntime, func(), error) {
	server := provideServerConfig(cfg)
	postgres := providePostgresConfig(cfg)
	client, cleanup, err := providePostgres(ctx, postgres)
	if err != nil {
		return nil, nil, err
	}
	serveRuntime := provideServeRuntime(server, client)
	return serveRuntime, func() {
		cleanup()
	}, nil
}
